/* eslint-disable react-refresh/only-export-components */
import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import {
  AlertTriangle, ArrowUpRight, BarChart3, Bot, CalendarDays, CheckCircle2,
  ChevronDown, ChevronRight, CircleAlert, Clock3, Download, Filter, Gauge,
  GitBranch, MapPin, MoreHorizontal, Pickaxe, RefreshCw, Settings2, ShieldAlert,
  SlidersHorizontal, TrendingDown, TrendingUp, Truck, X, Zap,
} from 'lucide-react'
import '../index.css'

const HOURLY = [
  { hour: '00', real: 0, plan: 0, forecast: 0 }, { hour: '02', real: 21800, plan: 24400, forecast: 23000 },
  { hour: '04', real: 49300, plan: 54800, forecast: 52000 }, { hour: '06', real: 74800, plan: 81400, forecast: 79000 },
  { hour: '08', real: 101400, plan: 108600, forecast: 105800 }, { hour: '10', real: 138900, plan: 148200, forecast: 145600 },
  { hour: '12', real: 165400, plan: 177300, forecast: 173600 }, { hour: '14', real: 186420, plan: 200000, forecast: 194800 },
]
const FLEET = [
  { id: 'CAT-793-21', state: 'Operativo', cycle: 29.8, payload: 224, updated: 'Hace 1 min' },
  { id: 'CAT-793-17', state: 'Alerta', cycle: 38.2, payload: 209, updated: 'Hace 2 min' },
  { id: 'CAT-793-09', state: 'Mantenimiento', cycle: null, payload: null, updated: '1 h 42 min' },
  { id: 'CAT-793-25', state: 'Alerta', cycle: 35.7, payload: 214, updated: 'Hace 4 min' },
  { id: 'CAT-793-31', state: 'Operativo', cycle: 28.9, payload: 221, updated: 'Hace 1 min' },
]
const EXCEPTIONS = [
  { process: 'Acarreo', asset: 'CAT-793-17', metric: 'Tiempo ciclo', actual: '38.2 min', target: '28 min', deviation: '+36%', duration: '2 h 18 m', severity: 'Alta' },
  { process: 'Flota', asset: 'CAT 793', metric: 'Disponibilidad', actual: '87.6%', target: '90%', deviation: '-2.4 pp', duration: '4 h 10 m', severity: 'Alta' },
  { process: 'Planta', asset: 'Circuito Cu', metric: 'Recuperación', actual: '89.4%', target: '90.2%', deviation: '-0.8 pp', duration: '1 h 46 m', severity: 'Media' },
]
const DEFAULT_FILTERS = { mine: 'Unidad Andina', pit: 'Fase 04', shift: 'Día', fleet: 'Todas las flotas', material: 'Todo material', area: 'Toda la operación' }

function App() {
  const [filtersOpen, setFiltersOpen] = useState(false)
  const [filters, setFilters] = useState(DEFAULT_FILTERS)
  const [area, setArea] = useState('Acarreo y flota')
  const [hoverPoint, setHoverPoint] = useState(HOURLY[HOURLY.length - 1])
  const [detail, setDetail] = useState(null)
  const [loading, setLoading] = useState(false)
  const [maintenanceError, setMaintenanceError] = useState(false)
  const [notice, setNotice] = useState('')
  const selectedFleet = filters.fleet !== 'Todas las flotas' ? filters.fleet : null
  const chips = Object.entries(filters).filter(([key, value]) => value !== DEFAULT_FILTERS[key]).map(([key, value]) => ({ key, label: `${filterLabel(key)}: ${value}` }))
  const updateFilter = (key, value) => setFilters((current) => ({ ...current, [key]: value }))
  const clearFilters = () => setFilters(DEFAULT_FILTERS)
  const flash = (text) => { setNotice(text); window.setTimeout(() => setNotice(''), 3200) }
  const refresh = () => { setLoading(true); window.setTimeout(() => { setLoading(false); flash('Indicadores operacionales actualizados') }, 900) }
  return <div className={`h-screen w-full overflow-x-hidden bg-[#f3f6f8] text-slate-900 ${detail ? 'overflow-hidden' : 'overflow-y-auto overscroll-contain'}`}><Topbar loading={loading} onRefresh={refresh} onExport={() => flash('Exportación preparada')} onError={() => setMaintenanceError(!maintenanceError)} /><main className="mx-auto max-w-[1440px] px-5 py-7 sm:px-7 xl:px-10"><Header /><FilterBar filters={filters} open={filtersOpen} setOpen={setFiltersOpen} update={updateFilter} chips={chips} clear={clearFilters} /><ExecutiveStory loading={loading} point={hoverPoint} setPoint={setHoverPoint} onDetail={setDetail} /><Attention onDetail={setDetail} /><section className="mt-7"><DiagnosticTabs active={area} setActive={setArea} />{area === 'Producción' && <ProductionDiagnostics onDetail={setDetail} />}{area === 'Acarreo y flota' && <HaulageDiagnostics selectedFleet={selectedFleet} setFleet={(fleet) => updateFilter('fleet', fleet)} onDetail={setDetail} />}{area === 'Planta' && <PlantDiagnostics onDetail={setDetail} />}{area === 'Mantenimiento' && <MaintenanceDiagnostics error={maintenanceError} retry={() => setMaintenanceError(false)} onDetail={setDetail} />}</section><section className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1.18fr)_minmax(330px,.82fr)]"><Exceptions onDetail={setDetail} /><Events /></section></main>{detail && <AnalyticsDrawer detail={detail} onClose={() => setDetail(null)} onSelectFleet={(fleet) => { updateFilter('fleet', fleet); setDetail(null); setArea('Acarreo y flota') }} />}{notice && <Toast>{notice}</Toast>}</div>
}

function Topbar({ loading, onRefresh, onExport, onError }) { return <header className="sticky top-0 z-30 border-b border-slate-800 bg-slate-950 text-white"><div className="mx-auto flex h-[70px] max-w-[1440px] items-center justify-between px-5 sm:px-7 xl:px-10"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-500 text-slate-950 shadow-lg shadow-amber-950/40"><Pickaxe size={18} /></span><div><p className="text-sm font-semibold">Andina Mining</p><p className="text-[11px] text-slate-400">Operations Intelligence</p></div></div><div className="flex items-center gap-2"><button type="button" onClick={onRefresh} className="hidden items-center gap-2 rounded-lg px-3 py-2 text-xs font-medium text-slate-300 hover:bg-white/10 sm:flex">{loading ? <RefreshCw size={15} className="animate-spin text-amber-300" /> : <CheckCircle2 size={15} className="text-emerald-400" />}{loading ? 'Recalculando' : 'Datos actualizados · hace 2 min'}</button><button type="button" onClick={onExport} className="rounded-lg p-2.5 text-slate-300 hover:bg-white/10" aria-label="Exportar"><Download size={18} /></button><button type="button" onClick={onError} className="rounded-lg p-2.5 text-slate-300 hover:bg-white/10" aria-label="Estado de fuentes"><MoreHorizontal size={18} /></button></div></div></header> }
function Header() { return <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-semibold text-amber-700"><Gauge size={15} />CONTROL OPERACIONAL</div><h1 className="mt-3 text-3xl font-semibold tracking-[-.045em] text-slate-950 sm:text-4xl">Centro de Control Operacional</h1><p className="mt-2 text-sm text-slate-500">Monitoreo integrado de producción, flota, planta y desempeño operacional.</p></div><div className="flex items-center gap-1 rounded-xl bg-white p-1 shadow-sm ring-1 ring-slate-200"><Period active>Hoy</Period><Period>24 h</Period><Period>7 días</Period><Period>30 días</Period><Period>Personalizado</Period></div></div> }
function Period({ children, active = false }) { return <button type="button" className={`rounded-lg px-2.5 py-2 text-xs font-semibold ${active ? 'bg-slate-950 text-white' : 'text-slate-500 hover:bg-slate-50'}`}>{children}</button> }

function FilterBar({ filters, open, setOpen, update, chips, clear }) { return <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex flex-wrap items-center gap-3"><div className="flex min-w-[220px] flex-1 items-center gap-2 px-2 text-sm text-slate-600"><Filter size={16} className="text-slate-400" /><span className="truncate">{filters.mine} · {filters.pit} · Turno {filters.shift}</span></div><button type="button" onClick={() => setOpen(!open)} className={`inline-flex h-10 items-center gap-2 rounded-xl border px-3 text-sm font-semibold ${open ? 'border-amber-200 bg-amber-50 text-amber-800' : 'border-slate-200 text-slate-700 hover:bg-slate-50'}`}><SlidersHorizontal size={16} />Filtros{chips.length ? <span className="rounded-md bg-amber-100 px-1.5 py-0.5 text-[11px]">{chips.length}</span> : null}</button>{chips.length ? <button type="button" onClick={clear} className="text-xs font-semibold text-slate-500 hover:text-slate-900">Limpiar</button> : null}</div>{chips.length > 0 && <div className="flex flex-wrap gap-2 px-1 pt-3">{chips.map((chip) => <button key={chip.key} type="button" onClick={() => update(chip.key, DEFAULT_FILTERS[chip.key])} className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-2.5 py-1.5 text-xs text-slate-600">{chip.label}<X size={13} /></button>)}</div>}{open && <div className="mt-3 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2 lg:grid-cols-4"><FilterSelect label="Mina" value={filters.mine} onChange={(value) => update('mine', value)}><option>Unidad Andina</option><option>Unidad Sur</option></FilterSelect><FilterSelect label="Tajo" value={filters.pit} onChange={(value) => update('pit', value)}><option>Fase 04</option><option>Fase 03</option></FilterSelect><FilterSelect label="Turno" value={filters.shift} onChange={(value) => update('shift', value)}><option>Día</option><option>Noche</option></FilterSelect><FilterSelect label="Flota" value={filters.fleet} onChange={(value) => update('fleet', value)}><option>Todas las flotas</option><option>CAT 793</option><option>CAT-793-17</option><option>CAT-793-21</option><option>CAT-793-25</option><option>EX-01</option><option>EX-02</option><option>EX-03</option><option>EX-04</option><option>Komatsu 930E</option></FilterSelect><FilterSelect label="Material" value={filters.material} onChange={(value) => update('material', value)}><option>Todo material</option><option>Alta ley</option><option>Baja ley</option></FilterSelect><FilterSelect label="Área" value={filters.area} onChange={(value) => update('area', value)}><option>Toda la operación</option><option>Mina</option><option>Planta</option><option>Mantenimiento</option></FilterSelect></div>}</section> }
function FilterSelect({ label, value, onChange, children }) { return <label><span className="mb-1.5 block text-[11px] font-semibold text-slate-500">{label}</span><div className="relative"><select value={value} onChange={(event) => onChange(event.target.value)} className="h-10 w-full appearance-none rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none focus:border-amber-500 focus:ring-2 focus:ring-amber-100">{children}</select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-3 text-slate-400" /></div></label> }

function ExecutiveStory({ loading, point, setPoint, onDetail }) { return <section className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1.46fr)_minmax(330px,.54fr)]"><article className="overflow-hidden rounded-2xl bg-slate-950 text-white shadow-xl shadow-slate-300/50"><div className="flex flex-wrap items-start justify-between gap-5 p-6"><div><p className="text-xs font-semibold uppercase tracking-[.13em] text-amber-300">Cumplimiento del plan</p><h2 className="mt-2 text-xl font-semibold tracking-[-.03em]">Producción real vs plan acumulado</h2></div><button type="button" onClick={() => onDetail('production')} className="rounded-xl bg-white/10 px-3 py-2 text-xs font-semibold text-slate-100 hover:bg-white/15">Investigar producción</button></div><div className="grid gap-4 px-6 sm:grid-cols-3"><MetricDark label="Real" value="186,420 t" hint="+4.2% vs ayer" /><MetricDark label="Plan acumulado" value="200,000 t" hint="-13,580 t de brecha" danger /><MetricDark label="Forecast cierre" value="194,800 t" hint="97.4% del plan" forecast /></div><div className="px-4 pb-4 pt-3 sm:px-6">{loading ? <div className="h-56 animate-pulse rounded-xl bg-slate-800" /> : <ProductionChart point={point} setPoint={setPoint} />}</div></article><aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-indigo-600">Turno actual</p><h2 className="mt-2 text-lg font-semibold tracking-[-.02em] text-slate-950">Avance proporcional</h2></div><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[11px] font-semibold text-amber-700">En atraso</span></div><div className="mt-6"><div className="flex items-end justify-between"><div><p className="text-4xl font-semibold tracking-[-.06em] text-slate-950">62%</p><p className="mt-1 text-sm text-slate-500">del turno transcurrido</p></div><div className="text-right"><p className="text-lg font-semibold text-rose-600">57%</p><p className="mt-1 text-xs text-slate-400">del plan producido</p></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[57%] rounded-full bg-amber-500" /></div><p className="mt-3 text-xs leading-5 text-slate-500">A esta hora se esperaban <b className="font-semibold text-slate-700">124,000 t</b>; la producción actual es <b className="font-semibold text-rose-600">118,400 t</b> (-4.5%).</p></div><div className="my-6 border-t border-slate-100" /><p className="text-xs font-semibold uppercase tracking-[.1em] text-slate-400">Forecast operacional</p><p className="mt-2 text-2xl font-semibold tracking-[-.04em] text-slate-950">62% <span className="text-sm font-medium text-slate-400">probabilidad de cumplir</span></p><p className="mt-2 text-sm leading-6 text-slate-500">Si recuperamos el ciclo objetivo, el cierre estimado sube a <b className="font-semibold text-emerald-700">202,300 t</b>.</p></aside></section> }
function MetricDark({ label, value, hint, danger = false, forecast = false }) { return <div><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-2xl font-semibold tracking-[-.04em]">{value}</p><p className={`mt-1.5 text-xs ${danger ? 'text-rose-300' : forecast ? 'text-violet-300' : 'text-emerald-300'}`}>{hint}</p></div> }

function ProductionChart({ point, setPoint }) { const width = 760; const height = 250; const max = 210000; const coord = (value, index) => [42 + index * 94, 210 - (value / max) * 170]; const line = (field) => HOURLY.map((row, index) => `${index ? 'L' : 'M'}${coord(row[field], index).join(' ')}`).join(' '); return <div className="relative"><svg viewBox={`0 0 ${width} ${height}`} className="h-56 w-full" role="img" aria-label="Producción acumulada real, plan y forecast por hora"><line x1="42" y1="210" x2="720" y2="210" stroke="#475569" strokeWidth="1" /><line x1="42" y1="125" x2="720" y2="125" stroke="#334155" strokeDasharray="4 6" /><line x1="42" y1="40" x2="720" y2="40" stroke="#334155" strokeDasharray="4 6" /><path d={line('plan')} fill="none" stroke="#94a3b8" strokeWidth="3" strokeDasharray="7 6" /><path d={line('forecast')} fill="none" stroke="#a78bfa" strokeWidth="3" strokeDasharray="3 5" /><path d={line('real')} fill="none" stroke="#fbbf24" strokeWidth="4" />{HOURLY.map((row, index) => { const [x, y] = coord(row.real, index); return <g key={row.hour} onMouseEnter={() => setPoint(row)} className="cursor-crosshair"><circle cx={x} cy={y} r="11" fill="transparent" /><circle cx={x} cy={y} r="3.5" fill="#fbbf24" /><text x={x} y="235" fill="#94a3b8" textAnchor="middle" fontSize="11">{row.hour}h</text></g> })}</svg><div className="pointer-events-none absolute right-3 top-3 rounded-xl border border-white/10 bg-slate-900/95 px-3 py-2.5 text-xs shadow-xl"><p className="font-semibold text-white">{point.hour}:00</p><p className="mt-1 text-amber-300">Real: {formatTons(point.real)}</p><p className="text-slate-300">Plan: {formatTons(point.plan)}</p><p className="text-violet-300">Forecast: {formatTons(point.forecast)}</p><p className="mt-1 text-rose-300">Desviación: {formatTons(point.real - point.plan)}</p></div><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-slate-400"><Legend color="bg-amber-400" label="Real" /><Legend dashed color="bg-slate-400" label="Plan" /><Legend dashed color="bg-violet-400" label="Forecast" /><span className="ml-auto">│ 13:42 Chancadora detenida</span></div></div> }

function Attention({ onDetail }) { const alerts = [{ title: 'Producción bajo plan', icon: TrendingDown, level: 'Crítica', context: 'Brecha estimada: -13,580 t · -6.8%', detail: 'production' }, { title: 'Tiempo de ciclo elevado', icon: Clock3, level: 'Alta', context: 'CAT 793: 31.4 min vs objetivo 28 min', detail: 'cycle' }, { title: 'Disponibilidad bajo objetivo', icon: Truck, level: 'Alta', context: 'Flota: 87.6% vs objetivo 90%', detail: 'availability' }, { title: 'Recuperación descendiendo', icon: TrendingDown, level: 'Media', context: '89.4% · 0.8 pp bajo objetivo', detail: 'recovery' }]; return <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold text-rose-600"><ShieldAlert size={16} />REQUIEREN ATENCIÓN</div><h2 className="mt-2 text-xl font-semibold tracking-[-.03em] text-slate-950">Desviaciones que afectan el turno</h2></div><button type="button" className="text-xs font-semibold text-indigo-600 hover:text-indigo-700">Ver centro de alertas</button></div><div className="mt-5 grid gap-3 lg:grid-cols-4">{alerts.map((alert) => <AlertCard key={alert.title} {...alert} onClick={() => onDetail(alert.detail)} />)}</div></section> }
function AlertCard({ title, icon, level, context, onClick }) { const Icon = icon; const tone = level === 'Crítica' ? 'border-rose-100 bg-rose-50/60 text-rose-700' : level === 'Alta' ? 'border-amber-100 bg-amber-50/60 text-amber-700' : 'border-indigo-100 bg-indigo-50/60 text-indigo-700'; return <button type="button" onClick={onClick} className={`rounded-xl border p-3.5 text-left transition hover:-translate-y-0.5 hover:shadow-md ${tone}`}><div className="flex items-center justify-between"><Icon size={17} /><Severity level={level} /></div><p className="mt-4 text-sm font-semibold text-slate-900">{title}</p><p className="mt-1.5 text-xs leading-5 text-slate-600">{context}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold">Investigar<ChevronRight size={13} /></span></button> }

function DiagnosticTabs({ active, setActive }) { return <div className="flex gap-1 overflow-x-auto border-b border-slate-200">{['Producción', 'Acarreo y flota', 'Planta', 'Mantenimiento'].map((item) => <button key={item} type="button" onClick={() => setActive(item)} className={`whitespace-nowrap border-b-2 px-3.5 py-3 text-sm font-semibold ${active === item ? 'border-amber-500 text-amber-800' : 'border-transparent text-slate-500 hover:text-slate-800'}`}>{item}</button>)}</div> }

function ProductionDiagnostics({ onDetail }) { return <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(330px,.9fr)]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="PRODUCCIÓN POR PROCESO" title="¿Dónde se pierde material?" action="Ver balance" /><div className="mt-8 space-y-4">{[['Extracción', 235600, 'bg-slate-700'], ['Trituración', 194200, 'bg-indigo-500'], ['Procesamiento', 186420, 'bg-amber-500'], ['Producto final', 165800, 'bg-emerald-500']].map(([name, value, color], index) => <div key={name}><div className="flex items-center justify-between text-sm"><span className="font-medium text-slate-700">{name}</span><span className="font-semibold text-slate-900">{formatTons(value)}</span></div><div className="mt-2 h-8 overflow-hidden rounded-lg bg-slate-100"><div className={`flex h-full items-center justify-end rounded-lg px-3 text-xs font-semibold text-white ${color}`} style={{ width: `${(value / 235600) * 100}%` }}>{index > 0 ? `-${formatTons([0, 41400, 7780, 20620][index])}` : 'Base mina'}</div></div></div>)}</div></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="CONTROL DE LEY" title="Calidad de alimentación" /><div className="mt-6 grid grid-cols-2 gap-3"><Kpi label="Ley planificada" value="0.81%" /><Kpi label="Ley mina" value="0.86%" positive /><Kpi label="Ley planta" value="0.84%" positive /><Kpi label="Desviación" value="+3.7%" positive /></div><button type="button" onClick={() => onDetail('grade')} className="mt-6 w-full rounded-xl bg-slate-50 px-3 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-100">Analizar variabilidad de ley</button></article></div> }

function HaulageDiagnostics({ selectedFleet, setFleet, onDetail }) { return <div className="mt-6 space-y-6"><div className="grid gap-6 xl:grid-cols-[minmax(0,1.12fr)_minmax(340px,.88fr)]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="TIEMPO DE CICLO" title="La cola en chancado explica la desviación" action="Ver detalle" onAction={() => onDetail('cycle')} /><div className="mt-6 grid grid-cols-[120px_1fr] gap-5"><div><p className="text-4xl font-semibold tracking-[-.06em] text-slate-950">31.4<span className="ml-1 text-lg text-slate-400">min</span></p><p className="mt-2 text-xs leading-5 text-rose-600">+12.1% sobre objetivo · deteriorándose</p></div><CycleStack /></div><div className="mt-6 grid grid-cols-3 gap-3"><Kpi label="Camiones operativos" value="38 / 44" /><Kpi label="Payload promedio" value="218 t" /><Kpi label="Velocidad media" value="26 km/h" /></div></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="ESTADO DE FLOTA" title="44 camiones" /><div className="mt-7 flex items-center justify-center"><FleetRing /></div><div className="mt-6 grid grid-cols-4 gap-2 text-center">{[['38', 'Operativos', 'text-emerald-700'], ['3', 'Planificado', 'text-indigo-700'], ['2', 'Correctivo', 'text-amber-700'], ['1', 'Detenido', 'text-rose-700']].map(([value, label, color]) => <div key={label}><p className={`text-lg font-semibold ${color}`}>{value}</p><p className="mt-1 text-[10px] text-slate-400">{label}</p></div>)}</div></article></div><div className="grid gap-6 xl:grid-cols-[minmax(0,1.12fr)_minmax(330px,.88fr)]"><Heatmap selected={selectedFleet} setFleet={setFleet} /><Scatter onDetail={onDetail} /></div><FleetMatrix selected={selectedFleet} setFleet={setFleet} onDetail={onDetail} /></div> }
function CycleStack() { const parts = [['Carga', 4.6, 'bg-indigo-500'], ['Viaje cargado', 11.8, 'bg-slate-700'], ['Descarga', 2.4, 'bg-emerald-500'], ['Viaje vacío', 9.1, 'bg-sky-500'], ['Cola', 3.5, 'bg-amber-500']]; return <div><div className="flex h-12 overflow-hidden rounded-xl">{parts.map(([name, value, color]) => <div key={name} className={`flex items-center justify-center border-r border-white/30 text-[10px] font-bold text-white ${color}`} style={{ width: `${(value / 31.4) * 100}%` }}>{value >= 3 ? value : ''}</div>)}</div><div className="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-slate-500">{parts.map(([name, value, color]) => <Legend key={name} color={color} label={`${name} ${value} min`} />)}</div><p className="mt-3 text-xs text-amber-700"><b>Cola:</b> 3.5 min · 1.7 min sobre referencia. Principal oportunidad de recuperación.</p></div> }
function FleetRing() { return <div className="relative flex h-40 w-40 items-center justify-center rounded-full" style={{ background: 'conic-gradient(#10b981 0 86%, #f59e0b 86% 93%, #ef4444 93% 100%)' }}><div className="flex h-28 w-28 flex-col items-center justify-center rounded-full bg-white"><span className="text-3xl font-semibold tracking-[-.05em] text-slate-950">87.6%</span><span className="mt-1 text-[10px] text-slate-400">disponible</span></div></div> }
function Heatmap({ selected, setFleet }) { const teams = ['EX-01', 'EX-02', 'EX-03', 'EX-04']; const values = [[3, 3, 2, 2, 3, 3, 2], [3, 2, 2, 1, 2, 2, 3], [2, 2, 1, 0, 1, 1, 2], [3, 3, 3, 2, 2, 3, 3]]; const colors = ['bg-rose-200', 'bg-amber-300', 'bg-amber-200', 'bg-emerald-300']; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="HEATMAP OPERACIONAL" title="Productividad por pala y hora" /><p className="mt-1 text-xs text-slate-500">Selecciona un equipo para aplicar cross-filtering.</p><div className="mt-6 grid grid-cols-[64px_repeat(7,minmax(25px,1fr))] gap-1.5 text-center text-[10px]">{['', '08', '09', '10', '11', '12', '13', '14'].map((label) => <span key={label} className="py-1 text-slate-400">{label}</span>)}{teams.flatMap((team, row) => [<button key={`${team}-name`} type="button" onClick={() => setFleet(team === selected ? 'Todas las flotas' : team)} className={`rounded-md px-1 text-left text-[10px] font-semibold ${selected === team ? 'bg-amber-100 text-amber-800' : 'text-slate-600'}`}>{team}</button>, ...values[row].map((value, index) => <button key={`${team}-${index}`} type="button" onClick={() => setFleet(team)} aria-label={`${team} a las ${index + 8}:00`} className={`h-8 rounded-md transition hover:ring-2 hover:ring-slate-400 ${colors[value]}`} />)])}</div><div className="mt-4 flex gap-3 text-[11px] text-slate-500"><Legend color="bg-emerald-300" label="Alto" /><Legend color="bg-amber-200" label="Medio" /><Legend color="bg-rose-200" label="Bajo" /></div></article> }
function Scatter({ onDetail }) { const points = [[208, 37], [220, 30], [224, 29], [209, 38], [214, 35], [221, 28], [216, 33], [225, 30]]; return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="ANÁLISIS DE VIAJES" title="Payload vs tiempo de ciclo" action="Ver viajes" onAction={() => onDetail('cycle')} /><div className="mt-5"><svg viewBox="0 0 310 195" className="h-48 w-full" role="img" aria-label="Dispersión de payload y tiempo de ciclo"><line x1="40" y1="160" x2="290" y2="160" stroke="#cbd5e1" /><line x1="40" y1="20" x2="40" y2="160" stroke="#cbd5e1" /><line x1="40" y1="72" x2="290" y2="72" stroke="#fca5a5" strokeDasharray="5 5" />{points.map(([payload, cycle], index) => <circle key={index} cx={40 + (payload - 200) * 8} cy={160 - (cycle - 24) * 9} r={index === 0 || index === 3 ? 6 : 4.5} fill={index === 0 || index === 3 ? '#ef4444' : '#6366f1'} opacity=".9" />)}<text x="170" y="188" textAnchor="middle" fill="#94a3b8" fontSize="10">Payload (t)</text><text x="12" y="96" fill="#94a3b8" fontSize="10" transform="rotate(-90 12 96)">Ciclo (min)</text></svg></div><p className="mt-2 text-xs leading-5 text-slate-500">Los outliers rojos corresponden a CAT-793-17 y CAT-793-25: alto ciclo con menor payload.</p></article> }
function FleetMatrix({ selected, setFleet, onDetail }) { return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4 px-5 py-5 sm:px-6"><div><div className="flex items-center gap-2 text-xs font-semibold text-indigo-600"><Truck size={16} />MATRIZ DE FLOTA</div><h2 className="mt-2 text-xl font-semibold tracking-[-.03em] text-slate-950">Equipos relevantes</h2></div>{selected && <button type="button" onClick={() => setFleet('Todas las flotas')} className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-800">Filtro activo: {selected}<X className="ml-1 inline" size={13} /></button>}</div><div className="overflow-x-auto"><div className="min-w-[700px]"><div className="grid grid-cols-[1.2fr_130px_100px_100px_130px_44px] gap-4 border-y border-slate-100 bg-slate-50/70 px-5 py-3 text-[10px] font-bold uppercase tracking-[.1em] text-slate-400 sm:px-6"><span>Equipo</span><span>Estado</span><span>Ciclo</span><span>Payload</span><span>Actualización</span><span /></div>{FLEET.map((item) => <div key={item.id} className={`group grid grid-cols-[1.2fr_130px_100px_100px_130px_44px] items-center gap-4 border-b border-slate-100 px-5 py-4 last:border-0 hover:bg-slate-50/80 sm:px-6 ${selected === item.id ? 'bg-amber-50/60' : ''}`}><button type="button" onClick={() => setFleet(item.id)} className="text-left text-sm font-semibold text-slate-800 hover:text-amber-800">{item.id}</button><FleetState state={item.state} /><span className="text-xs text-slate-700">{item.cycle ? `${item.cycle} min` : '—'}</span><span className="text-xs text-slate-700">{item.payload ? `${item.payload} t` : '—'}</span><span className="text-xs text-slate-500">{item.updated}</span><button type="button" onClick={() => onDetail(item.id === 'CAT-793-17' ? 'cycle' : 'availability')} className="rounded-lg p-2 text-slate-400 hover:bg-white hover:text-slate-700"><ChevronRight size={16} /></button></div>)}</div></div></article> }

function PlantDiagnostics({ onDetail }) { const tones = { slate: 'text-slate-700', indigo: 'text-indigo-700', amber: 'text-amber-700', violet: 'text-violet-700', sky: 'text-sky-700', emerald: 'text-emerald-700' }; return <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(330px,.9fr)]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="BALANCE MINA → PLANTA" title="Flujo de material y acumulaciones" /><div className="mt-7 grid gap-2 sm:grid-cols-6">{[['Extraído', '235.6k', 'slate'], ['Transportado', '218.2k', 'indigo'], ['Stockpile', '124k', 'amber'], ['Chancado', '194.2k', 'violet'], ['Planta', '186.4k', 'sky'], ['Producto', '165.8k', 'emerald']].map(([label, value, tone], index) => <div key={label} className="relative rounded-xl bg-slate-50 p-3 text-center"><p className="text-[10px] font-semibold text-slate-400">{label}</p><p className={`mt-2 text-sm font-semibold ${tones[tone]}`}>{value} t</p>{index < 5 && <ChevronRight size={15} className="absolute -right-2 top-1/2 hidden -translate-y-1/2 text-slate-300 sm:block" />}</div>)}</div><p className="mt-5 flex gap-2 rounded-xl bg-amber-50 p-3.5 text-xs leading-5 text-amber-900"><AlertTriangle size={16} className="shrink-0 text-amber-600" />El stockpile de mineral alto registra una acumulación superior a la ventana operativa prevista.</p></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="PLANTA" title="Proceso actual" action="Investigar planta" onAction={() => onDetail('recovery')} /><div className="mt-6 grid grid-cols-2 gap-3"><Kpi label="Throughput" value="8,420 t/h" sub="objetivo 8,700" warn /><Kpi label="Disponibilidad" value="94.1%" sub="estable" positive /><Kpi label="Utilización" value="91.7%" sub="+1.4 pp" positive /><Kpi label="Recuperación Cu" value="89.4%" sub="objetivo 90.2%" warn /></div></article><article className="xl:col-span-2 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="THROUGHPUT PLANTA" title="Real, objetivo y promedio móvil" /><MiniLineChart /></article></div> }
function MaintenanceDiagnostics({ error, retry, onDetail }) { if (error) return <section className="mt-6 rounded-2xl border border-rose-100 bg-white p-8 text-center shadow-sm"><WifiOff size={26} className="mx-auto text-rose-500" /><h2 className="mt-4 text-lg font-semibold text-slate-900">No pudimos cargar datos de mantenimiento</h2><p className="mt-1 text-sm text-slate-500">Producción, flota y planta siguen disponibles. La fuente CMMS no respondió.</p><button type="button" onClick={retry} className="mt-5 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Reintentar</button></section>; return <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(330px,.9fr)]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="SALUD DE EQUIPOS" title="Disponibilidad física · últimos 30 días" action="Ver equipos" onAction={() => onDetail('availability')} /><div className="mt-6 grid grid-cols-5 gap-3">{[['3', 'Críticos', 'text-rose-600'], ['42.6 h', 'Downtime', 'text-amber-700'], ['126 h', 'MTBF', 'text-slate-800'], ['4.8 h', 'MTTR', 'text-slate-800'], ['92%', 'Planificado', 'text-emerald-700']].map(([value, label, color]) => <div key={label}><p className={`text-lg font-semibold ${color}`}>{value}</p><p className="mt-1 text-[10px] text-slate-400">{label}</p></div>)}</div><AvailabilityChart /></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="PARETO DE FALLAS" title="Downtime acumulado" /><div className="mt-6 space-y-3">{[['Motor', 18.4], ['Sistema hidráulico', 10.2], ['Neumáticos', 6.8], ['Transmisión', 4.1], ['Otros', 3.1]].map(([name, value]) => <div key={name}><div className="flex justify-between text-xs"><span className="font-medium text-slate-700">{name}</span><span className="text-slate-500">{value} h</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-500" style={{ width: `${(value / 18.4) * 100}%` }} /></div></div>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">Motor y sistema hidráulico explican el <b className="font-semibold text-slate-700">67% del downtime</b>.</p></article></div> }

function Exceptions({ onDetail }) { return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between px-5 py-5 sm:px-6"><div><div className="flex items-center gap-2 text-xs font-semibold text-rose-600"><CircleAlert size={16} />EXCEPCIONES OPERATIVAS</div><h2 className="mt-2 text-xl font-semibold tracking-[-.03em] text-slate-950">Lo que requiere investigación</h2></div><button type="button" className="text-xs font-semibold text-indigo-600">Ver todas</button></div><div className="overflow-x-auto"><div className="min-w-[790px]"><div className="grid grid-cols-[100px_120px_1fr_90px_90px_90px_85px_80px] gap-4 border-y border-slate-100 bg-slate-50/70 px-5 py-3 text-[10px] font-bold uppercase tracking-[.1em] text-slate-400 sm:px-6"><span>Proceso</span><span>Activo</span><span>Indicador</span><span>Actual</span><span>Objetivo</span><span>Desviación</span><span>Duración</span><span>Severidad</span></div>{EXCEPTIONS.map((item) => <button key={item.asset} type="button" onClick={() => onDetail(item.metric === 'Tiempo ciclo' ? 'cycle' : item.metric === 'Disponibilidad' ? 'availability' : 'recovery')} className="grid w-full grid-cols-[100px_120px_1fr_90px_90px_90px_85px_80px] gap-4 border-b border-slate-100 px-5 py-4 text-left hover:bg-slate-50 sm:px-6"><span className="text-xs text-slate-600">{item.process}</span><span className="text-xs font-semibold text-slate-800">{item.asset}</span><span className="text-xs text-slate-700">{item.metric}</span><span className="text-xs font-semibold text-rose-600">{item.actual}</span><span className="text-xs text-slate-500">{item.target}</span><span className="text-xs font-semibold text-rose-600">{item.deviation}</span><span className="text-xs text-slate-500">{item.duration}</span><Severity level={item.severity} /></button>)}</div></div></article> }
function Events() { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle eyebrow="EVENTOS RELEVANTES" title="Qué explica el gráfico" /><ol className="mt-6 space-y-4">{[['13:42', 'Chancadora primaria detenida', 'amber'], ['13:51', 'Mantenimiento inició diagnóstico', 'indigo'], ['14:08', 'Chancadora reiniciada', 'emerald'], ['14:12', 'Throughput recuperándose', 'emerald']].map(([time, text, tone], index) => <li key={time} className="flex gap-3"><span className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${tone === 'amber' ? 'bg-amber-500 ring-4 ring-amber-100' : tone === 'emerald' ? 'bg-emerald-500' : 'bg-indigo-500'}`} /><div><p className="text-xs font-semibold text-slate-500">{time}</p><p className="mt-0.5 text-sm text-slate-700">{text}</p>{index === 0 && <p className="mt-1 text-xs text-amber-700">Impacto visible en la tendencia de throughput.</p>}</div></li>)}</ol><div className="mt-6 rounded-xl bg-slate-950 p-4 text-white"><div className="flex items-center gap-2 text-xs font-semibold text-amber-300"><Bot size={15} />INSIGHT AUTOMÁTICO</div><p className="mt-2 text-sm leading-6">El <b>61% de la desviación de producción</b> está asociada al incremento del tiempo de ciclo de acarreo.</p></div></article> }

function AnalyticsDrawer({ detail, onClose, onSelectFleet }) { const content = drawerContent(detail); return <><div className="fixed inset-0 z-40 bg-slate-950/35" role="presentation" /><aside role="dialog" aria-modal="true" aria-labelledby="analytics-title" className="fixed bottom-3 top-3 z-50 flex w-[min(460px,calc(100vw-1.5rem))] flex-col overflow-hidden rounded-2xl bg-white shadow-2xl shadow-slate-950/30" style={{ right: 'max(0.75rem, calc((100vw - 90rem) / 2))' }}><div className="border-b border-slate-100 px-5 py-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold text-amber-700">DRILL-DOWN ANALÍTICO</p><h2 id="analytics-title" className="mt-1 text-lg font-semibold tracking-[-.02em] text-slate-950">{content.title}</h2></div><button type="button" onClick={onClose} aria-label="Cerrar análisis" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><X size={18} /></button></div><div className="mt-4 flex items-end gap-4"><p className="text-3xl font-semibold tracking-[-.05em] text-slate-950">{content.value}</p><p className="mb-1 text-xs font-semibold text-rose-600">{content.delta}</p></div></div><div className="flex-1 overflow-y-auto px-5 py-5"><DrawerBlock title="Evolución últimas 24 h"><MiniLineChart alert /></DrawerBlock><DrawerBlock title={content.breakdownTitle}><div className="space-y-3">{content.breakdown.map(([name, value, width]) => <div key={name}><div className="flex justify-between text-xs"><span className="text-slate-600">{name}</span><span className="font-semibold text-slate-800">{value}</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-amber-500" style={{ width: `${width}%` }} /></div></div>)}</div></DrawerBlock><DrawerBlock title="Equipos con mayor desviación"><div className="space-y-2">{[['CAT-793-17', '38.2 min'], ['CAT-793-09', '36.8 min'], ['CAT-793-25', '35.7 min']].map(([fleet, value]) => <button type="button" key={fleet} onClick={() => onSelectFleet(fleet)} className="flex w-full items-center justify-between rounded-xl border border-slate-200 px-3.5 py-3 text-left hover:border-amber-200 hover:bg-amber-50"><span className="text-sm font-semibold text-slate-800">{fleet}</span><span className="text-xs font-semibold text-rose-600">{value}</span></button>)}</div></DrawerBlock><DrawerBlock title="Posibles causas"><ul className="space-y-2 text-sm leading-6 text-slate-600"><li>• Cola en chancado.</li><li>• Congestión en ruta norte.</li><li>• Menor velocidad promedio.</li></ul></DrawerBlock></div><div className="border-t border-slate-100 p-4"><button type="button" onClick={() => onSelectFleet('CAT-793-17')} className="flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white hover:bg-slate-800">Filtrar CAT-793-17<ChevronRight size={16} /></button></div></aside></> }
function drawerContent(detail) { const map = { production: { title: 'Producción real vs plan', value: '186,420 t', delta: '-6.8% vs plan', breakdownTitle: 'Procesos que explican la brecha', breakdown: [['Acarreo', '61% de impacto', 61], ['Chancado', '24% de impacto', 24], ['Disponibilidad flota', '15% de impacto', 15]] }, cycle: { title: 'Tiempo promedio de ciclo', value: '31.4 min', delta: '+12.1% sobre objetivo', breakdownTitle: 'Componentes del ciclo', breakdown: [['Carga', '4.6 min', 15], ['Viaje cargado', '11.8 min', 38], ['Descarga', '2.4 min', 8], ['Viaje vacío', '9.1 min', 29], ['Cola', '3.5 min', 18]] }, availability: { title: 'Disponibilidad física de flota', value: '87.6%', delta: '-2.4 pp bajo objetivo', breakdownTitle: 'Downtime por causa', breakdown: [['Motor', '18.4 h', 100], ['Sistema hidráulico', '10.2 h', 55], ['Neumáticos', '6.8 h', 37]] }, recovery: { title: 'Recuperación metalúrgica', value: '89.4%', delta: '-0.8 pp bajo objetivo', breakdownTitle: 'Variables relacionadas', breakdown: [['Ley alimentación', '0.84%', 84], ['Throughput', '8,420 t/h', 90], ['Granulometría', 'En rango', 74]] }, grade: { title: 'Variabilidad de ley', value: '0.84% Cu', delta: '+3.7% vs plan', breakdownTitle: 'Ley por origen', breakdown: [['Ley planificada', '0.81%', 81], ['Ley mina', '0.86%', 86], ['Ley planta', '0.84%', 84]] } }; return map[detail] || map.cycle }
function DrawerBlock({ title, children }) { return <section className="mb-6"><h3 className="mb-3 text-[11px] font-bold uppercase tracking-[.11em] text-slate-400">{title}</h3>{children}</section> }

function SectionTitle({ eyebrow, title, action, onAction }) { return <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-indigo-600">{eyebrow}</p><h2 className="mt-2 text-lg font-semibold tracking-[-.025em] text-slate-950">{title}</h2></div>{action && <button type="button" onClick={onAction} className="whitespace-nowrap text-xs font-semibold text-indigo-600 hover:text-indigo-700">{action}</button>}</div> }
function Kpi({ label, value, sub, positive = false, warn = false }) { return <div className="rounded-xl bg-slate-50 p-3.5"><p className="text-[11px] font-semibold text-slate-500">{label}</p><p className="mt-1.5 text-lg font-semibold tracking-[-.03em] text-slate-900">{value}</p>{sub && <p className={`mt-1 text-[11px] ${positive ? 'text-emerald-700' : warn ? 'text-amber-700' : 'text-slate-400'}`}>{sub}</p>}</div> }
function MiniLineChart({ alert = false }) { return <svg viewBox="0 0 400 125" className="h-32 w-full" role="img" aria-label="Tendencia operativa"><path d="M18 95L74 76L130 83L185 48L241 65L296 36L382 43" fill="none" stroke={alert ? '#f59e0b' : '#6366f1'} strokeWidth="3" /><path d="M18 73L74 68L130 63L185 58L241 54L296 49L382 45" fill="none" stroke="#94a3b8" strokeDasharray="6 5" strokeWidth="2" /><line x1="18" y1="100" x2="382" y2="100" stroke="#e2e8f0" /><text x="18" y="120" fontSize="10" fill="#94a3b8">08h</text><text x="190" y="120" fontSize="10" fill="#94a3b8">12h</text><text x="365" y="120" fontSize="10" fill="#94a3b8">16h</text></svg> }
function AvailabilityChart() { return <div className="mt-6"><MiniLineChart alert /><div className="mt-1 flex justify-between text-[11px] text-slate-400"><span>Real 87.6%</span><span>Objetivo 90%</span></div></div> }
function Severity({ level }) { const styles = { Crítica: 'bg-rose-100 text-rose-700', Alta: 'bg-amber-100 text-amber-700', Media: 'bg-indigo-100 text-indigo-700' }; return <span className={`inline-flex w-fit rounded-full px-2 py-1 text-[10px] font-semibold ${styles[level]}`}>{level}</span> }
function FleetState({ state }) { const styles = { Operativo: 'bg-emerald-50 text-emerald-700', Alerta: 'bg-amber-50 text-amber-700', Mantenimiento: 'bg-rose-50 text-rose-700' }; return <span className={`inline-flex w-fit rounded-full px-2 py-1 text-[10px] font-semibold ${styles[state]}`}>{state}</span> }
function Legend({ color, label, dashed = false }) { return <span className="inline-flex items-center gap-1.5"><span className={`h-2 w-2 rounded-full ${color} ${dashed ? 'opacity-70' : ''}`} />{label}</span> }
function Toast({ children }) { return <div role="status" className="fixed bottom-5 left-1/2 z-[60] flex -translate-x-1/2 items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-medium text-white shadow-2xl"><CheckCircle2 size={17} className="text-emerald-400" />{children}</div> }
function formatTons(value) { const sign = value < 0 ? '-' : ''; return `${sign}${Math.abs(value).toLocaleString('en-US')} t` }
function filterLabel(key) { return { mine: 'Mina', pit: 'Tajo', shift: 'Turno', fleet: 'Flota', material: 'Material', area: 'Área' }[key] }

createRoot(document.getElementById('root')).render(<App />)
