import { createElement, useEffect, useMemo, useRef, useState } from 'react'
import {
  Activity, AlertTriangle, ArrowLeft, BarChart3, BellRing, Building2, CheckCircle2,
  ChevronDown, ChevronUp, ChevronsUpDown, CircleUserRound, Clock3, CreditCard,
  FileText, Globe2, HardDrive, Headphones, HeartPulse, KeyRound, LayoutDashboard,
  LockKeyhole, Menu, MoreHorizontal, RefreshCcw, ScrollText, Search, Settings2,
  ShieldCheck, SlidersHorizontal, UserCog, UsersRound, X,
} from 'lucide-react'
import toast, { Toaster } from 'react-hot-toast'
import { ModuleHeader, ModuleTabs, DemoStatusBanner, EmptyTab, HelpPanel, Card } from './components/ModuleChrome'
import LandingManagement from './LandingManagement'
import PlanComparison from './PlanComparison'
import RoleTemplatesManagement from './RoleTemplatesManagement'
import TabLimites from '../pages/AdminSaaS/TabLimites'
import { PLAN_MODULES } from '../pages/AdminSaaS/planCapabilities'
import {
  canAdminAuthenticate, dashboardMetrics, defaultRouteFor, formatMoney, formatPlanLimit,
  moduleTabs, parseRoute, readRoute, seedPlans, seedTenantAdmins, seedTenants,
  subscriptionAccess, tenantUsage, toTenantSlug, validateEditor, writeRoute,
} from './domain'

const NAVIGATION = [
  { label:'', items:[['dashboard', 'Dashboard', LayoutDashboard]] },
  { label:'CLIENTES', items:[['negocios', 'Negocios', Building2], ['usuarios', 'Usuarios', UsersRound], ['soporte', 'Soporte', Headphones]] },
  { label:'SUSCRIPCIONES', items:[['planes', 'Planes y capacidades', CreditCard], ['suscripciones', 'Suscripciones', RefreshCcw]] },
  { label:'PLATAFORMA', items:[['operacion', 'Operación SaaS', HeartPulse], ['alertas', 'Alertas', BellRing]] },
  { label:'SISTEMA', items:[['auditoria', 'Auditoría', ScrollText], ['administradores', 'Administradores', UserCog], ['configuracion', 'Configuración', Settings2]] },
  { label:'MARKETING', items:[['landing', 'Landing Page', Globe2], ['analytics', 'Analytics', BarChart3]] },
]

const MODULE_META = {
  dashboard: { eyebrow:'CENTRO DE CONTROL', title:'Estado de la plataforma', description:'Prioriza riesgos operativos, comerciales y de seguridad antes de entrar al detalle.' },
  negocios: { eyebrow:'CLIENTES', title:'Negocios', description:'Administra el ciclo de vida y el contexto operativo de cada tenant.' },
  usuarios: { eyebrow:'USUARIOS Y ACCESOS', title:'Administración de usuarios', description:'Gestiona responsables, roles fijos y sesiones sin mezclar responsabilidades.' },
  soporte: { eyebrow:'SOPORTE', title:'Soporte y recuperación', description:'Revisa casos e intervenciones con acceso controlado y trazable.' },
  planes: { eyebrow:'OFERTA COMERCIAL', title:'Planes y capacidades', description:'Separa el catálogo, la capacidad contratada, los módulos y la comparación comercial.' },
  suscripciones: { eyebrow:'SUSCRIPCIONES', title:'Renovaciones y facturación', description:'Supervisa ingresos, vigencias y cobros sin mezclar estas decisiones con la oferta comercial.' },
  operacion: { eyebrow:'OPERACIÓN SAAS', title:'Salud y continuidad', description:'Mantén visible la disponibilidad, incidentes y medidas de continuidad.' },
  alertas: { eyebrow:'CENTRO DE ALERTAS', title:'Alertas de plataforma', description:'Prioriza lo que necesita intervención y conserva las reglas fuera de la bandeja.' },
  auditoria: { eyebrow:'AUDITORÍA', title:'Bitácora de plataforma', description:'Consulta trazabilidad administrativa con filtros, exportaciones controladas y retención.' },
  administradores: { eyebrow:'PLATAFORMA', title:'Administradores de plataforma', description:'Protege cuentas privilegiadas, sesiones, MFA y actividad administrativa.' },
  configuracion: { eyebrow:'CONFIGURACIÓN', title:'Configuración de plataforma', description:'Organiza valores globales, integraciones y funciones experimentales por separado.' },
  landing: { eyebrow:'CONTENIDO PÚBLICO', title:'Landing Page', description:'Administra contenido público, SEO y publicación sin mezclarlo con Analytics.' },
  analytics: { eyebrow:'ANALYTICS', title:'Crecimiento y conversión', description:'Entiende adquisición y conversión respetando consentimiento y privacidad.' },
}

const alertsSeed = [
  { id:'al-1', category:'Suscripción', severity:'Crítica', title:'Plan vence hoy', detail:'Logística Andina EIRL · Básico', state:'Abierta' },
  { id:'al-2', category:'Límites', severity:'Alta', title:'Capacidad de usuarios agotada', detail:'5 / 5 usuarios activos · Logística Andina EIRL', state:'Abierta' },
  { id:'al-3', category:'Seguridad', severity:'Alta', title:'MFA pendiente para PlatformAdmin', detail:'2 cuentas privilegiadas requieren enrolamiento', state:'Abierta' },
  { id:'al-4', category:'Operación', severity:'Información', title:'Backup diario verificado', detail:'Backup #BKP-20260829 completado y validado', state:'Resuelta' },
]

const auditSeed = [
  { id:'au-1', date:'29 ago · 10:42', actor:'Andrea Ramos', action:'Actualizó plan', resource:'Distribuciones Norte SAC', type:'Suscripción', result:'Exitoso' },
  { id:'au-2', date:'29 ago · 10:31', actor:'Sistema', action:'Verificó backup diario', resource:'Backup #BKP-20260829', type:'Operación', result:'Exitoso' },
  { id:'au-3', date:'29 ago · 09:15', actor:'Carlos Medina', action:'Inició sesión', resource:'PlatformAdmin', type:'Seguridad', result:'Exitoso' },
  { id:'au-4', date:'28 ago · 17:04', actor:'Andrea Ramos', action:'Consultó detalle', resource:'Comercial Pacífico SAC', type:'Soporte', result:'Exitoso' },
  { id:'au-5', date:'28 ago · 16:52', actor:'Sistema', action:'Detectó límite de usuarios', resource:'Logística Andina EIRL', type:'Alerta', result:'Requiere atención' },
]

const sessionsSeed = [
  { id:'s1', adminId:'a1', device:'Windows · Chrome', location:'Lima, Perú', ip:'190.12.•••.24', updated:'Ahora', active:true },
  { id:'s2', adminId:'a1', device:'Android · Chrome', location:'Lima, Perú', ip:'190.12.•••.91', updated:'Hace 2 días', active:true },
  { id:'s3', adminId:'a2', device:'macOS · Safari', location:'Arequipa, Perú', ip:'181.65.•••.10', updated:'Hace 3 h', active:true },
  { id:'s4', adminId:'a3', device:'Windows · Edge', location:'Cusco, Perú', ip:'200.48.•••.32', updated:'Hace 8 días', active:false },
]

const supportCases = [
  { id:'CASE-1042', tenant:'Logística Andina EIRL', subject:'Validar acceso de administrador', priority:'Alta', state:'Abierto', updated:'Hace 18 min' },
  { id:'CASE-1041', tenant:'Comercial Pacífico SAC', subject:'Consulta sobre límite de usuarios', priority:'Media', state:'En análisis', updated:'Hace 2 h' },
  { id:'CASE-1038', tenant:'Distribuciones Norte SAC', subject:'Solicitud de exportación', priority:'Baja', state:'Resuelto', updated:'Ayer' },
]

const badgeStyles = {
  Activo:'bg-emerald-500/10 text-emerald-300', Trial:'bg-blue-500/10 text-blue-300', Normal:'bg-emerald-500/10 text-emerald-300',
  'Por vencer':'bg-amber-500/10 text-amber-300', Atención:'bg-amber-500/10 text-amber-300', Pendiente:'bg-amber-500/10 text-amber-300',
  Abierto:'bg-amber-500/10 text-amber-300', 'En análisis':'bg-blue-500/10 text-blue-300', Resuelto:'bg-emerald-500/10 text-emerald-300',
  Suspendido:'bg-red-500/10 text-red-300', Cancelado:'bg-red-500/10 text-red-300', Archivado:'bg-white/8 text-[#9ba8b6]',
  Crítica:'bg-red-500/10 text-red-300', Alta:'bg-amber-500/10 text-amber-300', Media:'bg-blue-500/10 text-blue-300', Baja:'bg-white/8 text-[#9ba8b6]',
  Abierta:'bg-amber-500/10 text-amber-300', Resuelta:'bg-emerald-500/10 text-emerald-300', Exitoso:'bg-emerald-500/10 text-emerald-300',
  'Requiere atención':'bg-amber-500/10 text-amber-300', Activa:'bg-emerald-500/10 text-emerald-300', Revocada:'bg-white/8 text-[#9ba8b6]',
}

function useDemoStore(key, fallback) {
  const [value, setValue] = useState(() => {
    try { return JSON.parse(window.localStorage.getItem(key)) || fallback } catch { return fallback }
  })
  useEffect(() => { try { window.localStorage.setItem(key, JSON.stringify(value)) } catch { /* La maqueta sigue disponible sin almacenamiento. */ } }, [key, value])
  return [value, setValue]
}

function Badge({ children }) { return <span className={`inline-flex whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-semibold ${badgeStyles[children] || 'bg-white/8 text-[#9ba8b6]'}`}>{children}</span> }
function PrimaryButton({ children, className = '', ...props }) { return <button type="button" {...props} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#00c896] px-4 py-2.5 text-sm font-semibold text-[#082e1e] transition hover:bg-[#24d6aa] disabled:cursor-not-allowed disabled:opacity-45 ${className}`}>{children}</button> }
function SecondaryButton({ children, className = '', ...props }) { return <button type="button" {...props} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-white/8 bg-[#161d28] px-4 py-2.5 text-sm font-medium text-[#c5ced8] transition hover:bg-white/5 disabled:cursor-not-allowed disabled:opacity-45 ${className}`}>{children}</button> }

function Metric({ label, value, detail, tone = '#00c896' }) {
  return <article className="rounded-2xl border border-white/8 bg-[#161d28] p-6"><span className="block h-1.5 w-10 rounded-full" style={{ backgroundColor:tone }} /><p className="mt-4 text-xs font-semibold uppercase tracking-[.1em] text-[#718095]">{label}</p><p className="mt-2 text-3xl font-semibold tracking-[-.04em] text-[#e8edf2]">{value}</p><p className="mt-2 text-sm text-[#9ba8b6]">{detail}</p></article>
}

function MetricRow({ items }) { return <div className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-4">{items.map(item => <Metric key={item.label} {...item} />)}</div> }

function ConfirmDialog({ open, title, description, confirmLabel, cancelLabel = 'Cancelar', danger = false, onCancel, onConfirm }) {
  if (!open) return null
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/75 p-5" role="presentation">
    <section role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" aria-describedby="confirm-description" className="w-full max-w-md rounded-2xl border border-white/10 bg-[#161d28] p-6 shadow-2xl">
      <h2 id="confirm-title" className="text-lg font-semibold text-[#e8edf2]">{title}</h2><p id="confirm-description" className="mt-2 text-sm leading-6 text-[#9ba8b6]">{description}</p>
      <div className="mt-6 flex justify-end gap-2"><SecondaryButton onClick={onCancel}>{cancelLabel}</SecondaryButton><button type="button" onClick={onConfirm} className={`rounded-lg px-3.5 py-2.5 text-xs font-semibold ${danger ? 'bg-red-500 text-white hover:bg-red-400' : 'bg-[#00c896] text-[#082e1e]'}`}>{confirmLabel}</button></div>
    </section>
  </div>
}

function EditorModal({ editor, plans, tenants, records, onClose, onSave }) {
  const isTenant = editor.kind === 'tenant'
  const isPlan = editor.kind === 'plan'
  const isAdmin = editor.kind === 'admin'
  const initial = useMemo(() => editor.value ? { ...editor.value } : isTenant
    ? { nombre:'', nombreCorto:'', ruc:'', contacto:'', email:'', telefono:'', codigo:'', plan:plans[0]?.nombre || 'Básico', periodoPago:'Mensual', fechaInicio:'', fechaVencimiento:'', estadoPago:'Al día', politicaAcceso:'Suspender al vencer', diasGracia:3, suspensionManual:false, admins:1, usuariosActuales:0, usuariosLimite:0, ultimoAcceso:'Nunca', riesgo:'Normal', estado:'Activo' }
    : isPlan ? { nombre:'', precioMensual:0, maxUsuarios:1, maxAlmacenes:1, clientes:0, color:'#00c896', activo:true }
      : { tenant:tenants[0]?.nombre || '', nombre:'', email:'', tipo:'Admin Tenant', activo:true }, [editor, isPlan, isTenant, plans, tenants])
  const [form, setForm] = useState(initial)
  const [errors, setErrors] = useState({})
  const [discardOpen, setDiscardOpen] = useState(false)
  const firstInput = useRef(null)
  const dirty = JSON.stringify(form) !== JSON.stringify(initial)
  useEffect(() => { firstInput.current?.focus() }, [])
  useEffect(() => {
    const onKeyDown = event => { if (event.key === 'Escape') { event.preventDefault(); dirty ? setDiscardOpen(true) : onClose() } }
    document.addEventListener('keydown', onKeyDown)
    return () => document.removeEventListener('keydown', onKeyDown)
  }, [dirty, onClose])
  const set = (key, value) => setForm(current => ({
    ...current, [key]:value,
    ...(isTenant && key === 'nombre' && !editor.value && (!current.codigo || current.codigo === toTenantSlug(current.nombre)) ? { codigo:toTenantSlug(value) } : {}),
  }))
  const requestClose = () => dirty ? setDiscardOpen(true) : onClose()
  const submit = event => {
    event.preventDefault()
    const next = validateEditor(editor.kind, { ...form, id:editor.value?.id }, records)
    setErrors(next)
    if (!Object.keys(next).length) onSave(form)
  }
  const inputClass = key => `mt-2 w-full min-h-12 rounded-xl border bg-[#0e1117] px-4 py-3 text-[15px] text-[#e8edf2] outline-none transition focus:border-[#00c896] focus:ring-2 focus:ring-[#00c896]/20 ${errors[key] ? 'border-red-400' : 'border-white/8'}`
  const textField = (label, key, options = null, type = 'text', wide = false, hint = '') => <label className={`text-sm font-medium text-[#b2bdc9] ${wide ? 'md:col-span-2' : ''}`}>{label}{hint && <span className="mt-1.5 block text-xs font-normal leading-5 text-[#718095]">{hint}</span>}{options ? <select value={String(form[key] ?? '')} onChange={event => set(key, event.target.value)} className={inputClass(key)}>{options.map(option => <option key={option} value={option}>{option}</option>)}</select> : <input ref={key === 'nombre' ? firstInput : undefined} type={type} value={form[key] ?? ''} onChange={event => set(key, type === 'number' ? Number(event.target.value) : event.target.value)} className={inputClass(key)} />}{errors[key] && <span role="alert" className="mt-2 block text-xs text-red-300">{errors[key]}</span>}</label>
  const kindLabel = isTenant ? 'negocio' : isPlan ? 'plan' : 'administrador'
  return <><div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/75 p-4 md:p-8 backdrop-blur-sm" onMouseDown={event => { if (event.target === event.currentTarget) requestClose() }}>
    <form role="dialog" aria-modal="true" aria-labelledby="editor-title" onSubmit={submit} className="flex max-h-[calc(100vh-3rem)] w-full max-w-5xl flex-col overflow-hidden rounded-3xl border border-white/10 bg-[#161d28] shadow-2xl">
      <header className="flex items-start justify-between gap-5 border-b border-white/8 px-6 py-5 md:px-8 md:py-6"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#00c896]">{isTenant ? 'Negocios' : isPlan ? 'Planes' : 'Usuarios'}</p><h2 id="editor-title" className="mt-2 text-2xl font-semibold tracking-[-.02em]">{editor.value ? 'Editar' : 'Nuevo'} {kindLabel}</h2><p className="mt-2 text-sm text-[#718095]">Registro local de demostración · backend pendiente</p></div><button type="button" onClick={requestClose} aria-label="Cerrar formulario" className="rounded-xl p-3 text-[#9ba8b6] hover:bg-white/5"><X size={20} /></button></header>
      <div className="min-h-0 flex-1 overflow-y-auto px-6 py-7 md:px-8 md:py-8"><div className="grid gap-x-6 gap-y-6 md:grid-cols-2">
        {isTenant && <>{textField('Nombre del negocio *', 'nombre')}{textField('Nombre corto', 'nombreCorto')}{textField('RUC / identificación fiscal', 'ruc')}{textField('Contacto principal', 'contacto')}{textField('Correo', 'email', null, 'email')}{textField('Teléfono', 'telefono', null, 'tel')}{textField('Código URL *', 'codigo', null, 'text', true, 'Usa minúsculas, números y guiones.')}
          <div className="md:col-span-2 mt-2 border-t border-white/8 pt-6"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#718095]">Contrato y acceso</p></div>{textField('Plan contratado', 'plan', plans.map(plan => plan.nombre))}{textField('Período de pago', 'periodoPago', ['Mensual', 'Trimestral', 'Semestral', 'Anual'])}{textField('Fecha de inicio *', 'fechaInicio', null, 'date')}{textField('Fecha de vencimiento *', 'fechaVencimiento', null, 'date')}{textField('Estado del pago', 'estadoPago', ['Al día', 'Pendiente', 'Vencido'])}{textField('Política por falta de pago', 'politicaAcceso', ['Suspender al vencer', 'Control manual'])}{textField('Días de gracia', 'diasGracia', null, 'number')}
        </>}
        {isPlan && <>{textField('Nombre del plan *', 'nombre')}{textField('Precio mensual (PEN)', 'precioMensual', null, 'number')}{textField('Máximo de usuarios', 'maxUsuarios', null, 'number')}{textField('Máximo de almacenes', 'maxAlmacenes', null, 'number')}</>}
        {isAdmin && <>{textField('Negocio', 'tenant', tenants.map(tenant => tenant.nombre), 'text', true)}{textField('Nombre completo *', 'nombre', null, 'text', true)}{textField('Correo electrónico *', 'email', null, 'email', true)}{textField('Tipo de administrador', 'tipo', ['Admin Owner', 'Admin Tenant'], 'text', true)}<label className="md:col-span-2 flex items-start gap-4 rounded-2xl border border-white/8 bg-[#0e1117] p-5"><input type="checkbox" checked={form.activo === true} onChange={event => set('activo', event.target.checked)} className="mt-0.5 size-5 accent-[#00c896]" /><span><span className="block text-base font-medium text-[#e8edf2]">Administrador activo</span><span className="mt-1.5 block text-sm leading-6 text-[#718095]">Conserva el historial al desactivarlo, libera su cupo y bloquea el inicio de sesión.</span>{errors.activo && <span role="alert" className="mt-2 block text-xs text-red-300">{errors.activo}</span>}</span></label></>}
      </div></div>
      <footer className="flex items-center justify-end gap-3 border-t border-white/8 bg-[#161d28] px-6 py-5 md:px-8"><SecondaryButton onClick={requestClose}>Cancelar</SecondaryButton><button type="submit" className="inline-flex min-h-11 items-center justify-center rounded-xl bg-[#00c896] px-5 py-2.5 text-sm font-semibold text-[#082e1e] transition hover:bg-[#24d6aa]">Guardar cambios</button></footer>
    </form>
  </div><ConfirmDialog open={discardOpen} title="Tienes cambios sin guardar" description="Si sales ahora, perderás las modificaciones realizadas en este formulario." confirmLabel="Salir sin guardar" cancelLabel="Continuar editando" danger onCancel={() => setDiscardOpen(false)} onConfirm={onClose} /></>
}

function SortButton({ label, column, sort, onSort }) {
  const icon = sort.key !== column ? <ChevronsUpDown size={13} /> : sort.direction === 'asc' ? <ChevronUp size={13} /> : <ChevronDown size={13} />
  return <button type="button" onClick={() => onSort(column)} className="inline-flex items-center gap-1 text-left text-[11px] font-semibold uppercase tracking-wide text-[#718095] hover:text-[#e8edf2]">{label}{icon}</button>
}

function Pagination({ page, total, onChange }) {
  if (total <= 1) return null
  return <footer className="flex items-center justify-between gap-3 border-t border-white/8 px-4 py-3 text-xs text-[#718095]"><span>Página {page} de {total}</span><div className="flex gap-2"><SecondaryButton disabled={page === 1} onClick={() => onChange(page - 1)}>Anterior</SecondaryButton><SecondaryButton disabled={page === total} onClick={() => onChange(page + 1)}>Siguiente</SecondaryButton></div></footer>
}

function TenantTable({ tenants, onOpen, onEdit }) {
  const [query, setQuery] = useState('')
  const [sort, setSort] = useState({ key:'nombre', direction:'asc' })
  const [page, setPage] = useState(1)
  const [menuId, setMenuId] = useState(null)
  const perPage = 6
  const filtered = useMemo(() => tenants.filter(tenant => [tenant.nombre, tenant.plan, tenant.estado, tenant.riesgo].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a, b) => {
    const first = String(a[sort.key] ?? '').toLocaleLowerCase('es')
    const second = String(b[sort.key] ?? '').toLocaleLowerCase('es')
    return (first.localeCompare(second, 'es', { numeric:true }) || 0) * (sort.direction === 'asc' ? 1 : -1)
  }), [query, sort, tenants])
  const totalPages = Math.max(1, Math.ceil(filtered.length / perPage))
  const currentPage = Math.min(page, totalPages)
  const rows = filtered.slice((currentPage - 1) * perPage, currentPage * perPage)
  const updateSort = key => { setPage(1); setSort(current => current.key === key ? { key, direction:current.direction === 'asc' ? 'desc' : 'asc' } : { key, direction:'asc' }) }
  return <><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><label className="flex min-h-12 w-full max-w-xl items-center gap-3 rounded-xl border border-white/8 bg-[#161d28] px-4 py-3"><Search size={18} className="text-[#718095]" /><input value={query} onChange={event => { setQuery(event.target.value); setPage(1) }} placeholder="Buscar por negocio, plan o estado" className="min-w-0 flex-1 bg-transparent text-[15px] outline-none placeholder:text-[#718095]" /></label><PrimaryButton onClick={() => onEdit(null)}>Nuevo negocio</PrimaryButton></div>
    <div className="overflow-hidden rounded-2xl border border-white/8 bg-[#161d28]"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-[15px]"><thead className="bg-white/3"><tr><th className="sticky left-0 z-[1] bg-[#1a202b] px-5 py-4"><SortButton label="Negocio" column="nombre" sort={sort} onSort={updateSort} /></th><th className="px-5 py-4"><SortButton label="Plan" column="plan" sort={sort} onSort={updateSort} /></th><th className="px-5 py-4"><SortButton label="Estado" column="estado" sort={sort} onSort={updateSort} /></th><th className="px-5 py-4"><SortButton label="Admins." column="admins" sort={sort} onSort={updateSort} /></th><th className="px-5 py-4"><SortButton label="Usuarios" column="usuariosActuales" sort={sort} onSort={updateSort} /></th><th className="px-5 py-4"><SortButton label="Actividad" column="ultimoAcceso" sort={sort} onSort={updateSort} /></th><th className="px-5 py-4"><SortButton label="Riesgo" column="riesgo" sort={sort} onSort={updateSort} /></th><th className="sticky right-0 z-[1] bg-[#1a202b] px-5 py-4 text-right text-xs font-semibold uppercase tracking-wide text-[#718095]">Acciones</th></tr></thead><tbody>{rows.map(tenant => <tr key={tenant.id} className="border-t border-white/6"><td className="sticky left-0 z-[1] bg-[#161d28] px-5 py-5 font-medium text-[#e8edf2]">{tenant.nombre}</td><td className="px-5 py-5 text-[#9ba8b6]">{tenant.plan}</td><td className="px-5 py-5"><Badge>{tenant.estado}</Badge></td><td className="px-5 py-5 text-[#9ba8b6]">{tenant.admins}</td><td className="px-5 py-5 text-[#9ba8b6]">{tenantUsage(tenant)}</td><td className="px-5 py-5 text-[#9ba8b6]">{tenant.ultimoAcceso}</td><td className="px-5 py-5"><Badge>{tenant.riesgo}</Badge></td><td className="sticky right-0 z-[1] bg-[#161d28] px-5 py-5 text-right"><div className="relative inline-block"><button type="button" onClick={() => setMenuId(current => current === tenant.id ? null : tenant.id)} aria-label={`Acciones para ${tenant.nombre}`} aria-expanded={menuId === tenant.id} className="rounded-xl p-2.5 text-[#9ba8b6] hover:bg-white/6 hover:text-[#e8edf2]"><MoreHorizontal size={19} /></button>{menuId === tenant.id && <div className="absolute right-0 z-10 mt-1 w-44 rounded-xl border border-white/10 bg-[#1b2330] p-1.5 text-left shadow-xl"><button type="button" onClick={() => { setMenuId(null); onOpen(tenant) }} className="w-full rounded-lg px-3 py-2.5 text-left text-sm text-[#e8edf2] hover:bg-white/6">Abrir detalle</button><button type="button" onClick={() => { setMenuId(null); onEdit(tenant) }} className="w-full rounded-lg px-3 py-2.5 text-left text-sm text-[#9ba8b6] hover:bg-white/6">Editar negocio</button></div>}</div></td></tr>)}</tbody></table></div>{!rows.length && <EmptyTable onClear={() => setQuery('')} />}{rows.length > 0 && <Pagination page={currentPage} total={totalPages} onChange={setPage} />}</div></>
}

function EmptyTable({ onClear }) { return <div className="px-6 py-12 text-center"><p className="font-medium text-[#e8edf2]">No encontramos negocios con esos filtros.</p><button type="button" onClick={onClear} className="mt-3 text-xs font-medium text-[#00c896]">Limpiar búsqueda</button></div> }

function TenantDetailPage({ tenant, tab, onTabChange, onBack, onEdit, onChangeStatus }) {
  const tabs = [['resumen', 'Resumen'], ['suscripcion', 'Suscripción'], ['uso', 'Uso y límites'], ['administradores', 'Administradores'], ['seguridad', 'Seguridad'], ['auditoria', 'Auditoría'], ['soporte', 'Soporte']]
  const access = subscriptionAccess(tenant)
  const usage = [['Usuarios', tenantUsage(tenant), tenant.usuariosLimite ? Math.min(100, Math.round((tenant.usuariosActuales / tenant.usuariosLimite) * 100)) : 0, '#3b82f6'], ['Productos', '1,284 / 2,000', 64, '#00c896'], ['Almacenes', tenant.plan === 'Empresarial' ? '8 / ilimitado' : '3 / 5', 60, '#8b5cf6'], ['Almacenamiento', '4.8 GB / 10 GB', 48, '#f59e0b']]
  return <section><button type="button" onClick={onBack} className="mb-5 inline-flex items-center gap-2 text-xs font-medium text-[#9ba8b6] hover:text-[#e8edf2]"><ArrowLeft size={15} />Volver a negocios</button><ModuleHeader eyebrow="NEGOCIOS" title={tenant.nombre} description={`RUC ${tenant.ruc || '—'} · Código ${tenant.codigo || '—'} · detalle de demostración`} action={<div className="flex gap-2"><SecondaryButton onClick={() => onEdit(tenant)}>Editar</SecondaryButton><PrimaryButton onClick={() => onChangeStatus('Suspendido', true)}>Suspender</PrimaryButton></div>} /><div className="mb-5 flex flex-wrap items-center gap-2"><Badge>{tenant.estado}</Badge><Badge>{tenant.plan}</Badge><span className="text-xs text-[#718095]">Último acceso: {tenant.ultimoAcceso}</span></div><ModuleTabs tabs={tabs.map(([id, label]) => ({ id, label }))} active={tab} onChange={onTabChange} />
    {tab === 'resumen' && <><div className="mb-5 flex flex-wrap items-center gap-2"><SecondaryButton onClick={() => onChangeStatus(tenant.plan === 'Prueba gratuita' ? 'Trial' : 'Activo', false)}>Reactivar</SecondaryButton><details className="relative"><summary className="cursor-pointer list-none rounded-lg border border-white/8 bg-[#161d28] px-3.5 py-2.5 text-xs font-medium text-[#c5ced8]">Más acciones</summary><div className="absolute right-0 z-10 mt-2 w-44 rounded-xl border border-white/10 bg-[#1b2330] p-1 shadow-xl"><button type="button" onClick={() => onChangeStatus('Cancelado', false)} className="w-full rounded-lg px-3 py-2 text-left text-xs text-red-300 hover:bg-white/6">Cancelar negocio</button><button type="button" onClick={() => onChangeStatus('Archivado', false)} className="w-full rounded-lg px-3 py-2 text-left text-xs text-[#9ba8b6] hover:bg-white/6">Archivar</button></div></details></div><div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="grid gap-4 sm:grid-cols-2"><Card title="Suscripción"><InfoRow label="Plan" value={tenant.plan} /><InfoRow label="Vigencia" value={`${tenant.fechaInicio || '—'} — ${tenant.fechaVencimiento || '—'}`} /><InfoRow label="Pago" value={tenant.estadoPago || 'Pendiente'} /></Card><Card title="Actividad"><InfoRow label="Administradores" value={`${tenant.admins} activos`} /><InfoRow label="Usuarios activos" value={String(tenant.usuariosActuales || 0)} /><InfoRow label="Última operación" value="Hace 24 min" /></Card></div><Card title="Estado de acceso"><div className={`rounded-xl border p-4 ${access.allowed ? 'border-emerald-500/25 bg-emerald-500/5' : 'border-red-500/25 bg-red-500/5'}`}><p className={`font-semibold ${access.allowed ? 'text-emerald-300' : 'text-red-300'}`}>{access.label}</p><p className="mt-2 text-xs leading-5 text-[#9ba8b6]">La decisión es una simulación de frontend; el backend deberá validarla durante el inicio de sesión.</p></div><div className="mt-5"><div className="flex items-center justify-between text-sm"><span className="text-[#9ba8b6]">Salud del tenant</span><strong className="text-emerald-300">91%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#0e1117]"><div className="h-full w-[91%] rounded-full bg-emerald-400" /></div></div></Card></div></>}
    {tab === 'suscripcion' && <Card title="Suscripción y renovación"><InfoRow label="Plan contratado" value={tenant.plan} /><InfoRow label="Periodo" value={tenant.periodoPago || 'Mensual'} /><InfoRow label="Fecha de inicio" value={tenant.fechaInicio || '—'} /><InfoRow label="Próximo vencimiento" value={tenant.fechaVencimiento || '—'} /><InfoRow label="Estado de pago" value={tenant.estadoPago || 'Pendiente'} /></Card>}
    {tab === 'uso' && <Card title="Uso y límites"> <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{usage.map(([label, value, percent, color]) => <div key={label}><div className="flex justify-between gap-3 text-xs"><span className="text-[#9ba8b6]">{label}</span><strong className="text-[#e8edf2]">{value}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#0e1117]"><div className="h-full rounded-full" style={{ width:`${percent}%`, backgroundColor:color }} /></div></div>)}</div></Card>}
    {tab === 'administradores' && <Card title="Administradores del negocio"><p>El detalle de responsables se mostrará aquí al integrarse con el backend de usuarios.</p><PrimaryButton className="mt-5" onClick={() => onEdit(tenant)}>Editar negocio</PrimaryButton></Card>}
    {tab === 'seguridad' && <Card title="Seguridad"><InfoRow label="MFA" value="Por configurar" highlight /><InfoRow label="Último acceso" value={tenant.ultimoAcceso} /><InfoRow label="Acceso de soporte" value="Inactivo" /></Card>}
    {tab === 'auditoria' && <EmptyTab title="Auditoría del negocio" description="Los eventos aparecerán aquí filtrados por tenant cuando exista una fuente de auditoría autoritativa." />}
    {tab === 'soporte' && <EmptyTab title="Soporte asociado" description="Casos, intervenciones y accesos temporales se relacionarán a este negocio desde el módulo de Soporte." />}
  </section>
}

function InfoRow({ label, value, highlight = false }) { return <div className="flex items-center justify-between gap-5 border-b border-white/6 py-3 text-sm first:pt-0 last:border-0 last:pb-0"><span className="text-[#718095]">{label}</span><strong className={`text-right font-medium ${highlight ? 'text-amber-300' : 'text-[#e8edf2]'}`}>{value}</strong></div> }

export default function SuperAdminV2RefinedApp() {
  const [route, setRoute] = useState(readRoute)
  const [menuOpen, setMenuOpen] = useState(false)
  const [editor, setEditor] = useState(null)
  const [pendingTransition, setPendingTransition] = useState(null)
  const [tenants, setTenants] = useDemoStore('stockpro-superadmin-v2-tenants-v4', seedTenants)
  const [plans, setPlans] = useDemoStore('stockpro-superadmin-v2-plans-v3', seedPlans)
  const [admins, setAdmins] = useDemoStore('stockpro-superadmin-v2-tenant-admins-v2', seedTenantAdmins)
  const [sessions, setSessions] = useDemoStore('stockpro-superadmin-v2-admin-sessions', sessionsSeed)
  const [audit, setAudit] = useDemoStore('stockpro-superadmin-v2-audit-events', auditSeed)
  const routeInfo = parseRoute(route)
  const meta = MODULE_META[routeInfo.module] || MODULE_META.dashboard
  const metrics = useMemo(() => dashboardMetrics(tenants, plans), [plans, tenants])
  useEffect(() => { const sync = () => setRoute(readRoute()); window.addEventListener('hashchange', sync); return () => window.removeEventListener('hashchange', sync) }, [])
  const navigate = target => { const next = parseRoute(target).route; setRoute(next); writeRoute(next); setMenuOpen(false) }
  const changeTenantStatus = (tenant, state, manual = false) => setPendingTransition({ tenant, state, manual })
  const saveEditor = data => {
    if (editor.kind === 'tenant') {
      const record = { ...editor.value, ...data, id:editor.value?.id || `tenant-${Date.now()}`, usuarios:editor.value?.usuarios || tenantUsage(data), usuariosActuales:editor.value?.usuariosActuales ?? 0, usuariosLimite:editor.value?.usuariosLimite ?? 0, riesgo:editor.value?.riesgo || 'Normal', ultimoAcceso:editor.value?.ultimoAcceso || 'Nunca' }
      setTenants(current => editor.value ? current.map(item => item.id === record.id ? record : item) : [record, ...current])
      toast.success(editor.value ? 'Negocio actualizado.' : 'Negocio creado en la maqueta.')
    }
    if (editor.kind === 'plan') {
      const record = { ...editor.value, ...data, id:editor.value?.id || `plan-${Date.now()}`, clientes:editor.value?.clientes ?? 0, color:editor.value?.color || '#00c896', mrr:formatMoney((data.precioMensual || 0) * (editor.value?.clientes || 0)), limite:formatPlanLimit({ ...editor.value, ...data }) }
      setPlans(current => editor.value ? current.map(item => item.id === record.id ? record : item) : [...current, record])
      toast.success(editor.value ? 'Plan actualizado.' : 'Plan creado en la maqueta.')
    }
    if (editor.kind === 'admin') {
      const record = { ...editor.value, ...data, id:editor.value?.id || `admin-${Date.now()}` }
      setAdmins(current => editor.value ? current.map(item => item.id === record.id ? record : item) : [record, ...current])
      setAudit(current => [{ id:`audit-${Date.now()}`, date:'Ahora', actor:'SuperAdmin', action:editor.value ? 'Actualizó administrador' : 'Creó administrador', resource:`${record.nombre} · ${record.tenant}`, type:'Seguridad', result:'Exitoso' }, ...current])
      toast.success(editor.value ? 'Administrador actualizado.' : 'Administrador registrado en la maqueta.')
    }
    setEditor(null)
  }
  const tabItems = moduleTabs[routeInfo.module] || []
  const detailTenant = routeInfo.section === 'tenant-detail' ? tenants.find(tenant => tenant.id === routeInfo.tenantId) : null
  const updatePlan = { mutateAsync:async ({ id, ...changes }) => { setPlans(current => current.map(plan => plan.id === id ? { ...plan, ...changes, limite:formatPlanLimit({ ...plan, ...changes }) } : plan)); return { data:{ id, ...changes }, error:null } } }
  return <main className="min-h-screen bg-[#0e1117] text-[#e8edf2]"><header className="sticky top-0 z-30 flex min-h-[72px] items-center justify-between border-b border-white/8 bg-[#141920]/95 px-6 backdrop-blur md:px-8 xl:px-10"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-[#00c896]/15 text-[#00c896]"><ShieldCheck size={22} /></div><div><p className="text-base font-semibold">StockPro · SuperAdmin V2</p><p className="mt-0.5 text-xs text-[#718095]">Maqueta de evaluación</p></div></div><div className="flex items-center gap-3"><span className="hidden rounded-full border border-amber-500/25 bg-amber-500/10 px-3.5 py-2 text-xs font-semibold text-amber-300 sm:block">DATOS DE DEMOSTRACIÓN</span><button type="button" onClick={() => setMenuOpen(value => !value)} aria-expanded={menuOpen} aria-label="Abrir navegación" className="rounded-xl border border-white/8 p-3 text-[#9ba8b6] lg:hidden"><Menu size={19} /></button></div></header>
    <div className="grid w-full grid-cols-1 lg:grid-cols-[264px_minmax(0,1fr)]"><nav aria-label="Navegación de SuperAdmin" className={`${menuOpen ? 'block' : 'hidden'} border-b border-white/8 bg-[#0f1520] p-4 lg:block lg:min-h-[calc(100vh-72px)] lg:border-b-0 lg:border-r lg:px-4 lg:py-6`}>{NAVIGATION.map(group => <div key={group.label || 'general'} className="mb-5">{group.label && <p className="mb-2 px-3 text-[11px] font-semibold tracking-[.12em] text-[#5f6f80]">{group.label}</p>}{group.items.map(([id, label, Icon]) => <button type="button" key={id} onClick={() => navigate(defaultRouteFor(id))} aria-current={routeInfo.module === id ? 'page' : undefined} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition-colors ${routeInfo.module === id ? 'bg-[#00c896]/12 text-[#00c896]' : 'text-[#9ba8b6] hover:bg-white/5 hover:text-[#e8edf2]'}`}>{createElement(Icon, { size:17 })}{label}</button>)}</div>)}</nav>
      <section className="min-w-0 p-6 md:p-8 xl:px-10 xl:py-10 2xl:px-12">{detailTenant ? <TenantDetailPage tenant={detailTenant} tab={routeInfo.tab} onTabChange={tab => navigate(`negocios/${detailTenant.id}/${tab}`)} onBack={() => navigate('negocios/listado')} onEdit={tenant => setEditor({ kind:'tenant', value:tenant })} onChangeStatus={(state, manual) => changeTenantStatus(detailTenant, state, manual)} /> : <><ModuleHeader eyebrow={meta.eyebrow} title={meta.title} description={meta.description} action={routeInfo.module === 'negocios' ? <PrimaryButton onClick={() => setEditor({ kind:'tenant' })}>Nuevo negocio</PrimaryButton> : routeInfo.module === 'usuarios' && routeInfo.tab === 'administradores' ? <PrimaryButton onClick={() => setEditor({ kind:'admin' })}>Nuevo administrador</PrimaryButton> : routeInfo.module === 'planes' && routeInfo.tab === 'catalogo' ? <PrimaryButton onClick={() => setEditor({ kind:'plan' })}>Nuevo plan</PrimaryButton> : null} />{tabItems.length > 1 && <ModuleTabs tabs={tabItems.map(([id, label]) => ({ id, label }))} active={routeInfo.tab} onChange={tab => navigate(`${routeInfo.module}/${tab}`)} />}<ModuleView module={routeInfo.module} tab={routeInfo.tab} tenants={tenants} plans={plans} admins={admins} sessions={sessions} audit={audit} metrics={metrics} openTenant={tenant => navigate(`negocios/${tenant.id}/resumen`)} openEditor={(kind, value) => setEditor({ kind, value })} changeTenantStatus={changeTenantStatus} setSessions={setSessions} updatePlan={updatePlan} /></>}</section>
    </div>{editor && <EditorModal key={`${editor.kind}-${editor.value?.id || 'new'}`} editor={editor} plans={plans} tenants={tenants} records={{ tenants, plans, admins }} onClose={() => setEditor(null)} onSave={saveEditor} />}<ConfirmDialog open={Boolean(pendingTransition)} title={`Confirmar cambio a ${pendingTransition?.state || ''}`} description={`El negocio ${pendingTransition?.tenant?.nombre || ''} cambiará de estado. Esta acción quedará auditada cuando el backend esté disponible.`} confirmLabel="Confirmar cambio" danger={['Cancelado', 'Archivado'].includes(pendingTransition?.state)} onCancel={() => setPendingTransition(null)} onConfirm={() => { const item = pendingTransition; setTenants(current => current.map(tenant => tenant.id === item.tenant.id ? { ...tenant, estado:item.state, suspensionManual:item.manual } : tenant)); setAudit(current => [{ id:`audit-${Date.now()}`, date:'Ahora', actor:'SuperAdmin', action:`Cambió estado a ${item.state}`, resource:item.tenant.nombre, type:'Suscripción', result:'Exitoso' }, ...current]); toast.success('Estado actualizado en la maqueta.'); setPendingTransition(null) }} /><Toaster position="top-right" /></main>
}

function ModuleView({ module, tab, tenants, plans, admins, sessions, audit, metrics, openTenant, openEditor, setSessions, updatePlan }) {
  if (module === 'dashboard') return <Dashboard metrics={metrics} tenants={tenants} plans={plans} openTenant={openTenant} />
  if (module === 'negocios') return <Negocios tab={tab} tenants={tenants} openTenant={openTenant} openEditor={openEditor} />
  if (module === 'usuarios') return <Usuarios tab={tab} admins={admins} sessions={sessions} setSessions={setSessions} openEditor={openEditor} />
  if (module === 'planes') return <Planes tab={tab} plans={plans} tenants={tenants} openEditor={openEditor} updatePlan={updatePlan} />
  if (module === 'suscripciones') return <Subscriptions tab={tab} tenants={tenants} plans={plans} />
  if (module === 'soporte') return <Support tab={tab} />
  if (module === 'operacion') return <Operation tab={tab} />
  if (module === 'alertas') return <Alerts tab={tab} />
  if (module === 'auditoria') return <Audit tab={tab} audit={audit} />
  if (module === 'administradores') return <PlatformAdmins tab={tab} sessions={sessions} setSessions={setSessions} />
  if (module === 'configuracion') return <Settings tab={tab} />
  if (module === 'landing') return <Landing tab={tab} />
  if (module === 'analytics') return <Analytics tab={tab} />
  return null
}

function Dashboard({ metrics, tenants, plans, openTenant }) { const attention = tenants.filter(tenant => tenant.riesgo === 'Atención' || tenant.estado === 'Por vencer'); return <><MetricRow items={[{ label:'Tenants activos', value:metrics.activos, detail:`de ${metrics.totalTenants} registrados` }, { label:'MRR estimado', value:formatMoney(metrics.mrr), detail:'según planes de demostración', tone:'#f59e0b' }, { label:'Usuarios registrados', value:tenants.reduce((sum, tenant) => sum + (tenant.usuariosActuales || 0), 0), detail:'en tenants de prueba', tone:'#3b82f6' }, { label:'Requieren atención', value:attention.length, detail:'uso, vigencia o acceso', tone:'#ef4444' }]} /><div className="mt-6 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Card title="Requiere atención"><div className="divide-y divide-white/6">{attention.map(tenant => <button key={tenant.id} type="button" onClick={() => openTenant(tenant)} className="flex w-full items-center gap-3 py-3 text-left first:pt-0 last:pb-0"><AlertTriangle size={16} className="shrink-0 text-amber-400" /><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-[#e8edf2]">{tenant.nombre}</span><span className="mt-1 block text-xs text-[#718095]">{tenant.estado} · {tenant.riesgo}</span></span><span className="text-xs font-medium text-[#00c896]">Revisar</span></button>)}</div></Card><Card title="Actividad reciente"><div className="space-y-3 text-sm"><p><span className="text-emerald-300">●</span> Backup diario verificado</p><p><span className="text-amber-300">●</span> Renovación pendiente hoy</p><p><span className="text-blue-300">●</span> {plans.length} planes publicados</p></div></Card></div><HelpPanel>El dashboard solo resume la situación. Las altas, cambios y decisiones se realizan dentro del módulo correspondiente.</HelpPanel></> }

function Negocios({ tab, tenants, openTenant, openEditor }) { if (tab === 'listado') return <><TenantTable tenants={tenants} onOpen={openTenant} onEdit={tenant => openEditor('tenant', tenant)} /><HelpPanel>Usa el detalle de cada negocio para revisar suscripción, uso, administradores, seguridad, auditoría y soporte sin saturar el listado.</HelpPanel></>; if (tab === 'ciclo') return <><DemoStatusBanner>Las transiciones son locales. El backend deberá aplicar reglas de suspensión y reactivación de forma autoritativa.</DemoStatusBanner><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tenants.map(tenant => <Card key={tenant.id} title={tenant.nombre}><div className="flex items-center justify-between gap-3"><Badge>{tenant.estado}</Badge><span className="text-xs text-[#718095]">{tenant.plan}</span></div><p className="mt-4 text-xs leading-5">Trial → Activo → Gracia → Suspendido → Cancelado → Archivado</p><button type="button" onClick={() => openTenant(tenant)} className="mt-4 text-xs font-medium text-[#00c896]">Abrir detalle</button></Card>)}</div></>; return <><MetricRow items={[{ label:'Riesgo alto', value:'1', detail:'requiere atención hoy', tone:'#ef4444' }, { label:'Capacidad agotada', value:'2', detail:'límites al 100%', tone:'#f59e0b' }, { label:'Sin actividad', value:'1', detail:'más de 90 días', tone:'#3b82f6' }]} /><Card className="mt-5" title="Riesgos priorizados"><p>La prioridad combinará suscripción, uso, inactividad y alertas al conectarse las APIs.</p></Card></> }

function Usuarios({ tab, admins, sessions, setSessions, openEditor }) { if (tab === 'administradores') return <><div className="overflow-hidden rounded-2xl border border-white/8 bg-[#161d28]"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-white/3 text-[11px] uppercase tracking-wide text-[#718095]"><tr><th className="px-4 py-3">Administrador</th><th className="px-4 py-3">Negocio</th><th className="px-4 py-3">Rol</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3 text-right">Acciones</th></tr></thead><tbody>{admins.map(admin => <tr key={admin.id} className="border-t border-white/6"><td className="px-4 py-4"><p className="font-medium text-[#e8edf2]">{admin.nombre}</p><p className="mt-1 text-xs text-[#718095]">{admin.email}</p></td><td className="px-4 py-4 text-[#9ba8b6]">{admin.tenant}</td><td className="px-4 py-4"><Badge>{admin.tipo}</Badge></td><td className="px-4 py-4"><Badge>{canAdminAuthenticate(admin) ? 'Activo' : 'Inactivo'}</Badge></td><td className="px-4 py-4 text-right"><button type="button" onClick={() => openEditor('admin', admin)} className="text-xs font-medium text-[#00c896]">Editar</button></td></tr>)}</tbody></table></div></div></>; if (tab === 'roles') return <RoleTemplatesManagement />; if (tab === 'asignaciones') return <EmptyTab title="Asignaciones de roles" description="Esta vista mostrará qué usuario tiene qué rol en cada negocio cuando se conecte el modelo de permisos." />; if (tab === 'sesiones') return <SessionList admins={admins} sessions={sessions} setSessions={setSessions} />; return <><Card title="Reglas de acceso"><div className="grid gap-3 md:grid-cols-2"><Rule title="Owner protegido" description="No permitir dejar un negocio sin al menos un Owner activo." /><Rule title="Cupos de plan" description="Las cuentas activas consumen cupo; las inactivas conservan historial y liberan capacidad." /><Rule title="Auditoría" description="Altas, cambios de rol, bloqueos y revocaciones deben quedar registrados." /><Rule title="Mínimo privilegio" description="Los roles fijos definen alcance; los tenants no crean permisos de plataforma." /></div></Card><HelpPanel>Las reglas muestran el modelo de negocio. Su enforcement real corresponde al backend y al motor de autorización.</HelpPanel></> }

function Rule({ title, description }) { return <div className="rounded-xl bg-white/3 p-4"><p className="font-medium text-[#e8edf2]">{title}</p><p className="mt-1 text-xs leading-5 text-[#9ba8b6]">{description}</p></div> }
function SessionList({ admins, sessions, setSessions }) { const [adminId, setAdminId] = useState(admins[0]?.id || ''); const visible = sessions.filter(session => session.adminId === adminId); return <><DemoStatusBanner>Revocar una sesión afecta solo estos datos locales; todavía no invalida tokens reales.</DemoStatusBanner><Card title="Sesiones por administrador"><label className="block max-w-md text-xs font-medium text-[#9ba8b6]">Administrador<select value={adminId} onChange={event => setAdminId(event.target.value)} className="mt-1.5 w-full rounded-lg border border-white/8 bg-[#0e1117] px-3 py-2.5 text-sm text-[#e8edf2]">{admins.map(admin => <option key={admin.id} value={admin.id}>{admin.nombre} · {admin.tenant}</option>)}</select></label><div className="mt-5 divide-y divide-white/6">{visible.map(session => <div key={session.id} className="flex flex-wrap items-center gap-4 py-4"><CircleUserRound className="text-[#718095]" size={24} /><div className="min-w-[210px] flex-1"><p className="font-medium text-[#e8edf2]">{session.device}</p><p className="mt-1 text-xs text-[#718095]">{session.location} · {session.ip} · {session.updated}</p></div><Badge>{session.active ? 'Activa' : 'Revocada'}</Badge><button type="button" disabled={!session.active} onClick={() => { setSessions(current => current.map(item => item.id === session.id ? { ...item, active:false, updated:'Revocada ahora' } : item)); toast.success('Sesión revocada en la maqueta.') }} className="text-xs font-medium text-red-300 disabled:opacity-40">Revocar</button></div>)}{!visible.length && <p className="py-6 text-sm text-[#718095]">Este administrador no tiene sesiones registradas.</p>}</div></Card></> }

function Planes({ tab, plans, tenants, openEditor, updatePlan }) { if (tab === 'catalogo') return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{plans.map(plan => <Card key={plan.id} title={plan.nombre}><div className="flex items-center justify-between"><span className="size-2.5 rounded-full" style={{ backgroundColor:plan.color }} /><Badge>{plan.activo === false ? 'Archivado' : 'Activo'}</Badge></div><p className="mt-5 text-2xl font-semibold text-[#e8edf2]">{formatMoney(plan.precioMensual)}</p><p className="mt-1 text-xs text-[#718095]">{plan.clientes || 0} clientes · {plan.limite}</p><button type="button" onClick={() => openEditor('plan', plan)} className="mt-5 text-xs font-medium text-[#00c896]">Editar plan</button></Card>)}</div>; if (tab === 'capacidades') return <TabLimites planes={plans} negocios={tenants} actualizarPlan={updatePlan} toast={(message, type) => type === 'error' ? toast.error(message) : toast.success(message)} />; if (tab === 'modulos') return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{PLAN_MODULES.map(module => <Card key={module.key} title={module.label}><p>{module.desc}</p><p className="mt-3 text-xs text-[#00c896]">Disponible según plan contratado</p></Card>)}</div>; return <PlanComparison plans={plans} /> }

function Subscriptions({ tab, tenants, plans }) { if (tab === 'resumen') return <MetricRow items={[{ label:'MRR estimado', value:formatMoney(plans.reduce((total, plan) => total + (plan.precioMensual || 0) * (plan.clientes || 0), 0)), detail:'ingresos mensuales de prueba' }, { label:'Renovaciones próximas', value:'3', detail:'durante los próximos 7 días', tone:'#f59e0b' }, { label:'Pagos pendientes', value:'2', detail:'requieren seguimiento', tone:'#ef4444' }]} />; if (tab === 'renovaciones') return <Card title="Próximas renovaciones"><div className="divide-y divide-white/6">{tenants.map(tenant => <div key={tenant.id} className="grid gap-2 py-4 sm:grid-cols-[110px_1fr_auto]"><span className="text-xs text-[#718095]">{tenant.fechaVencimiento || 'Por definir'}</span><span><span className="block font-medium text-[#e8edf2]">{tenant.nombre}</span><span className="mt-1 block text-xs text-[#718095]">{tenant.plan}</span></span><Badge>{tenant.estado}</Badge></div>)}</div></Card>; return <><DemoStatusBanner>Documentos, pasarela de pago y conciliación permanecen pendientes de integración.</DemoStatusBanner><EmptyTab title="Facturación y pagos" description="Las facturas, intentos de cobro y regularizaciones se consultarán desde esta pestaña sin mezclarla con las renovaciones." /></> }

function Support({ tab }) { if (tab === 'casos') return <><DemoStatusBanner>Los casos son datos de demostración. No existe persistencia, API ni acceso real a las cuentas de clientes.</DemoStatusBanner><Card title="Casos recientes"><div className="divide-y divide-white/6">{supportCases.map(item => <div key={item.id} className="grid gap-3 py-4 sm:grid-cols-[100px_1fr_auto]"><span className="text-xs font-medium text-[#00c896]">{item.id}</span><div><p className="font-medium text-[#e8edf2]">{item.subject}</p><p className="mt-1 text-xs text-[#718095]">{item.tenant} · {item.updated}</p></div><div className="flex gap-2"><Badge>{item.priority}</Badge><Badge>{item.state}</Badge></div></div>)}</div></Card></>; if (tab === 'intervenciones' || tab === 'accesos') return <><DemoStatusBanner>Las intervenciones requieren aprobación, alcance y duración antes de habilitar acceso a un negocio.</DemoStatusBanner><EmptyTab title={tab === 'intervenciones' ? 'Intervenciones de soporte' : 'Accesos temporales'} description="La creación y revocación estarán disponibles al integrar APIs auditadas y un flujo de aprobación." /></>; if (tab === 'historial') return <EmptyTab title="Historial de casos" description="Los casos cerrados y sus resultados se conservarán aquí con sus evidencias." />; return <Card title="Procedimiento obligatorio"><div className="grid gap-4 md:grid-cols-2">{[['1', 'Registrar caso', 'Motivo, tenant, solicitante y evidencia.'], ['2', 'Verificar identidad', 'Nunca recuperar acceso solo por llamada o mensaje.'], ['3', 'Aprobar intervención', 'Alcance y duración antes de habilitar modo soporte.'], ['4', 'Auditar y cerrar', 'Inicio, fin, acciones y resultado comunicado.']].map(([number, title, description]) => <div key={number} className="flex gap-3 rounded-xl bg-white/3 p-4"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-[#00c896]/15 text-xs font-semibold text-[#00c896]">{number}</span><div><p className="font-medium text-[#e8edf2]">{title}</p><p className="mt-1 text-xs leading-5 text-[#9ba8b6]">{description}</p></div></div>)}</div></Card> }

function Operation({ tab }) { if (tab === 'salud') return <MetricRow items={[{ label:'Salud de plataforma', value:'96%', detail:'servicios críticos operativos', tone:'#22c55e' }, { label:'Backups verificados', value:'1 / 1', detail:'última prueba hoy, 03:00', tone:'#3b82f6' }, { label:'Alertas abiertas', value:'3', detail:'2 comerciales · 1 acceso', tone:'#f59e0b' }]} />; if (tab === 'incidentes') return <Card title="Incidentes activos"><p>No existen incidentes críticos en los datos de demostración.</p></Card>; return <><DemoStatusBanner>Backups, restauraciones y runbooks se muestran como información de evaluación; todavía no ejecutan operaciones reales.</DemoStatusBanner><div className="grid gap-4 md:grid-cols-2"><Card title="Último respaldo"><p className="font-medium text-[#e8edf2]">BKP-20260829 · Verificado</p><p className="mt-2 text-xs">Hoy, 03:00 · PostgreSQL</p></Card><Card title="Continuidad"><p>Responsables, simulacros, comunicación y procedimiento de recuperación.</p></Card></div></> }

function Alerts({ tab }) { const [filter, setFilter] = useState('Todas'); const visible = filter === 'Todas' ? alertsSeed : alertsSeed.filter(alert => alert.category === filter); if (tab === 'reglas') return <><DemoStatusBanner>Las reglas definirán fuentes, umbrales, severidad, responsables y escalamiento al integrar el backend.</DemoStatusBanner><EmptyTab title="Reglas de alertas" description="Esta sección mantendrá la configuración fuera de la bandeja operativa." /></>; return <><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{['Todas', 'Suscripción', 'Límites', 'Seguridad', 'Operación'].map(item => <button type="button" key={item} onClick={() => setFilter(item)} className={`rounded-lg px-3 py-2 text-xs font-medium ${filter === item ? 'bg-[#00c896] text-[#082e1e]' : 'border border-white/8 bg-[#161d28] text-[#9ba8b6] hover:bg-white/5'}`}>{item}</button>)}</div><Badge>{visible.filter(alert => alert.state === 'Abierta').length} abiertas</Badge></div><div className="space-y-3">{visible.map(alert => <article key={alert.id} className="flex flex-wrap items-center gap-4 rounded-2xl border border-white/8 bg-[#161d28] p-4"><span className={`size-2.5 rounded-full ${alert.severity === 'Crítica' ? 'bg-red-400' : alert.severity === 'Alta' ? 'bg-amber-400' : 'bg-blue-400'}`} /><div className="min-w-[220px] flex-1"><p className="font-medium text-[#e8edf2]">{alert.title}</p><p className="mt-1 text-xs text-[#718095]">{alert.detail}</p></div><Badge>{alert.category}</Badge><Badge>{alert.state}</Badge><span className="text-xs text-[#718095]">Detalle con backend</span></article>)}</div></> }

function Audit({ tab, audit }) { const [filter, setFilter] = useState('Todos'); const [sort, setSort] = useState({ key:'date', direction:'desc' }); const visible = useMemo(() => audit.filter(event => filter === 'Todos' || event.type === filter).sort((a, b) => String(a[sort.key] || '').localeCompare(String(b[sort.key] || '')) * (sort.direction === 'asc' ? 1 : -1)), [audit, filter, sort]); const updateSort = key => setSort(current => current.key === key ? { key, direction:current.direction === 'asc' ? 'desc' : 'asc' } : { key, direction:'asc' }); if (tab === 'exportaciones') return <EmptyTab title="Exportaciones auditadas" description="Cada descarga registrará solicitante, motivo, alcance y resultado." />; if (tab === 'retencion') return <><DemoStatusBanner>La inmutabilidad y retención definitiva de eventos depende del backend.</DemoStatusBanner><div className="grid gap-4 md:grid-cols-2"><Card title="Retención">Define plazos, archivo, acceso y eliminación controlada.</Card><Card title="Integridad">Verifica orden temporal, actor auténtico y ausencia de secretos.</Card></div></>; return <><div className="mb-4 flex flex-wrap gap-2">{['Todos', 'Seguridad', 'Suscripción', 'Operación', 'Soporte', 'Alerta'].map(item => <button type="button" key={item} onClick={() => setFilter(item)} className={`rounded-lg px-3 py-2 text-xs font-medium ${filter === item ? 'bg-[#00c896] text-[#082e1e]' : 'border border-white/8 bg-[#161d28] text-[#9ba8b6] hover:bg-white/5'}`}>{item}</button>)}</div><div className="overflow-hidden rounded-2xl border border-white/8 bg-[#161d28]"><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="bg-white/3"><tr>{[['Fecha', 'date'], ['Actor', 'actor'], ['Acción', 'action'], ['Recurso', 'resource'], ['Tipo', 'type'], ['Resultado', 'result']].map(([label, key]) => <th key={key} className="px-4 py-3"><SortButton label={label} column={key} sort={sort} onSort={updateSort} /></th>)}</tr></thead><tbody>{visible.map(event => <tr key={event.id} className="border-t border-white/6"><td className="px-4 py-4 text-xs text-[#718095]">{event.date}</td><td className="px-4 py-4 font-medium text-[#e8edf2]">{event.actor}</td><td className="px-4 py-4 text-[#9ba8b6]">{event.action}</td><td className="px-4 py-4 text-[#9ba8b6]">{event.resource}</td><td className="px-4 py-4"><Badge>{event.type}</Badge></td><td className="px-4 py-4"><Badge>{event.result}</Badge></td></tr>)}</tbody></table></div>{!visible.length && <EmptyTable onClear={() => setFilter('Todos')} />}</div></> }

function PlatformAdmins({ tab, sessions, setSessions }) { if (tab === 'cuentas') return <Card title="Cuentas privilegiadas"><div className="divide-y divide-white/6">{['Andrea Ramos', 'Carlos Medina'].map(name => <div key={name} className="flex items-center justify-between py-4"><div><p className="font-medium text-[#e8edf2]">{name}</p><p className="mt-1 text-xs text-[#718095]">PlatformAdmin · MFA pendiente</p></div><Badge>Activo</Badge></div>)}</div></Card>; if (tab === 'mfa') return <><DemoStatusBanner>El enrolamiento MFA real depende del proveedor de identidad y sus APIs.</DemoStatusBanner><MetricRow items={[{ label:'MFA activo', value:'0 / 2', detail:'implementación pendiente', tone:'#f59e0b' }, { label:'Incumplimientos', value:'2', detail:'requieren atención', tone:'#ef4444' }]} /></>; if (tab === 'actividad') return <Card title="Actividad privilegiada"><p className="text-sm">Las acciones de plataforma se consultarán desde la auditoría con filtros por actor y seguridad.</p></Card>; return <SessionList admins={[{ id:'a1', nombre:'Andrea Ramos', tenant:'Plataforma' }]} sessions={sessions.filter(session => session.adminId === 'a1')} setSessions={setSessions} /> }

function Settings({ tab }) { if (tab === 'experimentos') return <><DemoStatusBanner>ACE y Approval Engine permanecen en evaluación y todavía no controlan la aplicación actual.</DemoStatusBanner><div className="grid gap-4 md:grid-cols-2"><Card title="Access Control Engine · ACE">Contratos, aislamiento, observabilidad y aprobación formal pendientes.</Card><Card title="Approval Engine">Idempotencia, eventos y validación de fallos pendientes.</Card></div></>; const copy = tab === 'integraciones' ? ['Integraciones', 'Servicios externos, contratos y estado de conexión.'] : ['Configuración general', 'Nombre de plataforma, zona horaria, notificaciones y políticas globales.']; return <><DemoStatusBanner /><EmptyTab title={copy[0]} description={copy[1]} /></> }

function Landing({ tab }) { if (tab === 'contenido') return <LandingManagement />; if (tab === 'seo') return <EmptyTab title="SEO y redes sociales" description="Título, descripción, Open Graph, imágenes y datos estructurados." />; return <><DemoStatusBanner /><EmptyTab title="Publicación versionada" description="Borradores, versión publicada, responsable y fecha de publicación." /></> }

function Analytics({ tab }) { if (tab === 'resumen') return <MetricRow items={[{ label:'Visitas del mes', value:'2,840', detail:'+12% vs. periodo anterior', tone:'#3b82f6' }, { label:'Solicitudes de demo', value:'86', detail:'3.0% de conversión' }, { label:'Trials iniciados', value:'24', detail:'28% desde solicitud', tone:'#8b5cf6' }]} />; if (tab === 'conversion') return <Card title="Embudo de conversión"><div className="divide-y divide-white/6">{[['Visitas', '2,840', '100%'], ['Solicitudes', '86', '3.0%'], ['Trials', '24', '0.8%'], ['Clientes', '9', '0.3%']].map(([label, value, ratio]) => <div key={label} className="grid grid-cols-3 py-3"><span>{label}</span><strong className="text-center text-[#e8edf2]">{value}</strong><span className="text-right text-[#718095]">{ratio}</span></div>)}</div></Card>; if (tab === 'adquisicion') return <EmptyTab title="Fuentes de adquisición" description="Campañas, referencias, búsqueda orgánica y atribución." />; return <><DemoStatusBanner>Debe definirse el proveedor analítico y el consentimiento antes de medir usuarios reales.</DemoStatusBanner><EmptyTab title="Consentimiento y privacidad" description="Cookies, finalidades, revocación y estado de instrumentación." /></> }
