/* eslint-disable react-refresh/only-export-components */
import { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import {
  ArrowLeft, ArrowRight, BadgeCheck, BriefcaseBusiness, Check, CheckCircle2,
  ChevronDown, FileCheck2, HeartPulse, Landmark, MoreHorizontal,
  Pencil, Plus, Search, ShieldCheck, Trash2, UserRound, UsersRound, X,
} from 'lucide-react'
import '../index.css'

const INITIAL_PEOPLE = [
  { id:'p-01', name:'Valeria Paredes', initials:'VP', role:'Analista de operaciones', start:'01 set 2026', pension:'AFP Integra', health:'EsSalud', status:'Completa', updated:'Hoy' },
  { id:'p-02', name:'Mateo Cárdenas', initials:'MC', role:'Coordinador de almacén', start:'18 ago 2026', pension:'ONP', health:'EsSalud', status:'Completa', updated:'Ayer' },
  { id:'p-03', name:'Luciana Fernández', initials:'LF', role:'Asistente comercial', start:'15 set 2026', pension:'Pendiente', health:'Pendiente', status:'Pendiente', updated:'Hace 2 h' },
  { id:'p-04', name:'Diego Ramos', initials:'DR', role:'Auxiliar de despacho', start:'04 ago 2026', pension:'AFP Prima', health:'EPS Pacífico', status:'Completa', updated:'04 ago' },
]

const EMPTY_FORM = { documentType:'DNI', document:'', firstName:'', lastName:'', role:'', startDate:'', pension:'AFP', afp:'Integra', health:'EsSalud', eps:'', dependent:false }
const STEPS = [{ id:1, title:'Persona', short:'Datos básicos' },{ id:2, title:'Cobertura', short:'Salud y pensión' },{ id:3, title:'Confirmar', short:'Revisión final' }]
const inputStyle = 'h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-300 focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100'

function Avatar({ initials, color = 'bg-indigo-100 text-indigo-700', size = 'md' }) { return <span className={`inline-flex shrink-0 items-center justify-center rounded-full font-semibold ${size === 'lg' ? 'h-12 w-12 text-sm' : 'h-9 w-9 text-xs'} ${color}`}>{initials}</span> }
function Status({ children }) { const pending=children==='Pendiente'; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold ${pending?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}`}><span className={`h-1.5 w-1.5 rounded-full ${pending?'bg-amber-500':'bg-emerald-500'}`} />{children}</span> }
function Field({ label, children }) { return <label className="block"><span className="text-[12px] font-semibold text-slate-700">{label}</span><div className="mt-1.5">{children}</div></label> }
function Select({ children, ...props }) { return <div className="relative"><select {...props} className={`${inputStyle} appearance-none pr-9`}>{children}</select><ChevronDown size={16} className="pointer-events-none absolute right-3 top-3 text-slate-400" /></div> }

function App() {
  const [people, setPeople] = useState(INITIAL_PEOPLE)
  const [view, setView] = useState('list')
  const [form, setForm] = useState(EMPTY_FORM)
  const [step, setStep] = useState(1)
  const [filter, setFilter] = useState('Todos')
  const [query, setQuery] = useState('')
  const [openMenu, setOpenMenu] = useState(null)
  const [selected, setSelected] = useState(null)
  const [removeCandidate, setRemoveCandidate] = useState(null)
  const [toast, setToast] = useState('')
  const visiblePeople = useMemo(() => people.filter(person => (filter === 'Todos' || person.status === filter) && `${person.name} ${person.role}`.toLowerCase().includes(query.toLowerCase())), [people, filter, query])
  const showWizard = (person = null) => { setSelected(person); setForm(person ? { ...EMPTY_FORM, firstName:person.name.split(' ')[0], lastName:person.name.split(' ').slice(1).join(' '), role:person.role, pension:person.pension.startsWith('ONP')?'ONP':'AFP', afp:person.pension.replace('AFP ','') || 'Integra', health:person.health.startsWith('EPS')?'EPS':'EsSalud', eps:person.health.replace('EPS ','') } : EMPTY_FORM); setStep(1); setView('wizard'); setOpenMenu(null) }
  const updateForm = (key,value) => setForm(current => ({ ...current, [key]:value }))
  const required = form.document && form.firstName && form.lastName && form.role && form.startDate
  const save = () => { const name=`${form.firstName} ${form.lastName}`.trim(); const record={ id:selected?.id||`p-${Date.now()}`, name, initials:name.split(' ').map(word=>word[0]).slice(0,2).join(''), role:form.role, start:new Date(`${form.startDate}T00:00:00`).toLocaleDateString('es-PE',{day:'2-digit',month:'short',year:'numeric'}), pension:form.pension==='AFP'?`AFP ${form.afp}`:'ONP', health:form.health==='EPS'?`EPS ${form.eps||'por confirmar'}`:'EsSalud', status:'Completa', updated:'Ahora' }; setPeople(current=>selected?current.map(person=>person.id===selected.id?record:person):[record,...current]); setView('list'); setToast(selected?'Ficha actualizada correctamente':'Afiliación registrada correctamente'); setTimeout(()=>setToast(''),3500) }
  return <div className="min-h-screen bg-[#fbfbfc] text-slate-900"><Topbar view={view} cancel={()=>setView('list')} /><main className="mx-auto max-w-6xl px-5 py-8 lg:px-8 lg:py-10">{view==='list'?<PeopleList people={visiblePeople} total={people.length} filter={filter} setFilter={setFilter} query={query} setQuery={setQuery} onNew={()=>showWizard()} onEdit={showWizard} openMenu={openMenu} setOpenMenu={setOpenMenu} onDelete={person=>{setRemoveCandidate(person); setOpenMenu(null)}} />:<AffiliationWizard form={form} set={updateForm} step={step} setStep={setStep} required={required} onCancel={()=>setView('list')} onSave={save} editing={Boolean(selected)} />}</main>{toast && <div role="status" className="fixed bottom-5 left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 rounded-2xl bg-slate-900 px-4 py-3 text-sm font-medium text-white shadow-2xl"><CheckCircle2 size={18} className="text-emerald-400"/>{toast}</div>}{removeCandidate && <RemoveDialog person={removeCandidate} onCancel={()=>setRemoveCandidate(null)} onConfirm={()=>{setPeople(current=>current.filter(x=>x.id!==removeCandidate.id)); setRemoveCandidate(null); setToast('Registro retirado de la vista')}} />}</div>
}

function Topbar({ view, cancel }) { return <header className="border-b border-slate-200/80 bg-white"><div className="mx-auto flex h-[72px] max-w-6xl items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-950 text-sm font-bold text-white">N</div><div><p className="text-sm font-semibold tracking-[-.02em] text-slate-950">Nómina</p><p className="text-[11px] text-slate-400">Gestión de personas</p></div></div>{view==='wizard'?<button type="button" onClick={cancel} className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold text-slate-500 hover:bg-slate-50 hover:text-slate-900"><X size={17}/>Cancelar</button>:<div className="hidden items-center gap-2 text-xs text-slate-400 sm:flex"><ShieldCheck size={15} className="text-emerald-500"/>Información confidencial</div>}</div></header> }

function PeopleList({ people, total, filter, setFilter, query, setQuery, onNew, onEdit, openMenu, setOpenMenu, onDelete }) { return <><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-semibold text-indigo-600">Personal</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em] text-slate-950 sm:text-4xl">Personas y afiliaciones</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">Revisa el estado de cada ficha o registra una nueva incorporación.</p></div><button type="button" onClick={onNew} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white shadow-lg shadow-slate-200 transition hover:bg-slate-800"><Plus size={17}/>Nueva afiliación</button></div><div className="mt-9 flex flex-wrap items-center justify-between gap-4"><div className="flex rounded-xl bg-slate-100 p-1">{['Todos','Pendiente','Completa'].map(item=><button key={item} onClick={()=>setFilter(item)} className={`rounded-lg px-3 py-2 text-xs font-semibold transition ${filter===item?'bg-white text-slate-900 shadow-sm':'text-slate-500 hover:text-slate-700'}`}>{item}{item==='Todos'&&<span className="ml-1.5 text-slate-400">{total}</span>}</button>)}</div><label className="flex h-10 w-full max-w-xs items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 transition focus-within:border-indigo-500 focus-within:ring-4 focus-within:ring-indigo-100"><Search size={16} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none placeholder:text-slate-300" placeholder="Buscar una persona" /></label></div><section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-[minmax(230px,1.5fr)_minmax(180px,1fr)_minmax(120px,.6fr)_40px] gap-4 border-b border-slate-100 px-5 py-3 text-[11px] font-bold uppercase tracking-[.1em] text-slate-400"><span>Persona</span><span className="hidden sm:block">Afiliaciones</span><span className="hidden md:block">Estado</span><span /></div>{people.length ? people.map(person=><PersonRow key={person.id} person={person} onEdit={()=>onEdit(person)} open={openMenu===person.id} setOpen={value=>setOpenMenu(value?person.id:null)} onDelete={()=>onDelete(person)} />):<div className="px-6 py-14 text-center"><UsersRound size={24} className="mx-auto text-slate-300"/><p className="mt-3 text-sm font-semibold text-slate-800">No encontramos personas</p><p className="mt-1 text-sm text-slate-500">Prueba con otra búsqueda o crea una nueva afiliación.</p></div>}</section><p className="mt-4 text-xs text-slate-400">Mostrando {people.length} de {total} registros · La ficha se puede completar o actualizar en cualquier momento.</p></> }

function PersonRow({ person, onEdit, open, setOpen, onDelete }) { return <div className="group grid grid-cols-[minmax(230px,1.5fr)_minmax(180px,1fr)_minmax(120px,.6fr)_40px] items-center gap-4 border-b border-slate-100 px-5 py-4 last:border-0 hover:bg-slate-50/80"><button onClick={onEdit} className="flex min-w-0 items-center gap-3 text-left"><Avatar initials={person.initials} color={person.status==='Pendiente'?'bg-amber-100 text-amber-700':'bg-indigo-100 text-indigo-700'}/><span className="min-w-0"><span className="block truncate text-sm font-semibold text-slate-900">{person.name}</span><span className="mt-0.5 block truncate text-xs text-slate-500">{person.role} · Ingreso {person.start}</span></span></button><div className="hidden sm:block"><p className="truncate text-xs font-medium text-slate-700">{person.pension}</p><p className="mt-1 truncate text-xs text-slate-400">{person.health}</p></div><div className="hidden md:block"><Status>{person.status}</Status><p className="mt-1.5 text-[11px] text-slate-400">Actualizado {person.updated}</p></div><div className="relative"><button onClick={()=>setOpen(!open)} aria-label={`Acciones para ${person.name}`} className="rounded-lg p-2 text-slate-400 opacity-100 hover:bg-white hover:text-slate-700 sm:opacity-0 sm:group-hover:opacity-100"><MoreHorizontal size={18}/></button>{open&&<div className="absolute right-0 top-9 z-10 w-40 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl"><button onClick={onEdit} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-xs font-medium text-slate-700 hover:bg-slate-50"><Pencil size={14}/>Editar ficha</button><button onClick={onDelete} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-xs font-medium text-rose-600 hover:bg-rose-50"><Trash2 size={14}/>Retirar</button></div>}</div></div> }

function AffiliationWizard({ form, set, step, setStep, required, onCancel, onSave, editing }) { const next=()=>{if(step===1&&!required)return; setStep(Math.min(3,step+1))}; return <><button type="button" onClick={onCancel} className="mb-7 flex items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-slate-900"><ArrowLeft size={16}/>Volver a personal</button><div className="mx-auto max-w-4xl"><div className="mb-8 text-center"><span className="inline-flex items-center gap-1.5 rounded-full bg-indigo-50 px-3 py-1.5 text-[11px] font-bold text-indigo-700"><FileCheck2 size={14}/>{editing?'Editar ficha':'Nueva afiliación'}</span><h1 className="mt-4 text-3xl font-semibold tracking-[-.035em] text-slate-950 sm:text-4xl">{editing?'Actualiza la afiliación':'Registra una afiliación'}</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-500">{editing?'Mantén la cobertura de la persona actualizada.':'Un proceso corto para dejar lista su ficha laboral.'}</p></div><div className="mx-auto mb-8 max-w-2xl"><StepNav step={step} setStep={setStep}/></div><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_260px]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">{step===1&&<PersonStep form={form} set={set}/>} {step===2&&<CoverageStep form={form} set={set}/>} {step===3&&<ConfirmStep form={form}/>}<div className="mt-8 flex items-center justify-between border-t border-slate-100 pt-5"><button type="button" onClick={()=>setStep(Math.max(1,step-1))} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold text-slate-500 hover:bg-slate-50 ${step===1?'invisible':''}`}><ArrowLeft size={16}/>Anterior</button>{step<3?<button type="button" disabled={step===1&&!required} onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-100 transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:shadow-none">Continuar<ArrowRight size={16}/></button>:<button type="button" onClick={onSave} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-100 transition hover:bg-indigo-700"><Check size={17}/>Guardar ficha</button>}</div>{step===1&&!required&&<p className="mt-3 text-right text-xs text-amber-600">Completa los datos obligatorios para continuar.</p>}</section><DraftCard form={form} step={step}/></div></div></> }

function StepNav({ step, setStep }) { return <ol className="grid grid-cols-3 gap-2">{STEPS.map(item=><li key={item.id}><button type="button" disabled={item.id>step} onClick={()=>setStep(item.id)} className={`flex w-full items-center gap-2 rounded-xl p-2.5 text-left ${item.id===step?'bg-indigo-50':'disabled:cursor-default'}`}><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[11px] font-bold ${item.id<step?'bg-emerald-500 text-white':item.id===step?'bg-indigo-600 text-white':'bg-slate-100 text-slate-400'}`}>{item.id<step?<Check size={14}/>:item.id}</span><span className="min-w-0"><span className={`block truncate text-xs font-semibold ${item.id<=step?'text-slate-800':'text-slate-400'}`}>{item.title}</span><span className="hidden truncate text-[10px] text-slate-400 sm:block">{item.short}</span></span></button></li>)}</ol> }

function PersonStep({ form, set }) { return <><FormHeader icon={UserRound} label="Paso 1 · Identidad" title="Datos esenciales" text="Solo lo necesario para crear la ficha laboral de la persona."/><div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo de documento"><Select value={form.documentType} onChange={e=>set('documentType',e.target.value)}><option>DNI</option><option>Carné de extranjería</option><option>Pasaporte</option></Select></Field><Field label="Número de documento"><input autoFocus value={form.document} onChange={e=>set('document',e.target.value)} className={inputStyle} placeholder="Ej. 72648159"/></Field><Field label="Nombres"><input value={form.firstName} onChange={e=>set('firstName',e.target.value)} className={inputStyle} placeholder="Ej. Valeria"/></Field><Field label="Apellidos"><input value={form.lastName} onChange={e=>set('lastName',e.target.value)} className={inputStyle} placeholder="Ej. Paredes"/></Field></div><div className="my-7 border-t border-slate-100"/><div className="grid gap-4 sm:grid-cols-2"><Field label="Cargo"><input value={form.role} onChange={e=>set('role',e.target.value)} className={inputStyle} placeholder="Ej. Analista de operaciones"/></Field><Field label="Fecha de ingreso"><input type="date" value={form.startDate} onChange={e=>set('startDate',e.target.value)} className={inputStyle}/></Field></div></> }

function CoverageStep({ form, set }) { return <><FormHeader icon={HeartPulse} label="Paso 2 · Cobertura" title="Elige sus afiliaciones" text="Selecciona la cobertura vigente. Los documentos se pueden adjuntar después."/><p className="mb-3 text-[11px] font-bold uppercase tracking-[.12em] text-slate-400">Pensión</p><div className="grid gap-3 sm:grid-cols-2"><OptionCard active={form.pension==='AFP'} onClick={()=>set('pension','AFP')} icon={Landmark} title="AFP" text="Fondo privado de pensiones"/><OptionCard active={form.pension==='ONP'} onClick={()=>set('pension','ONP')} icon={ShieldCheck} title="ONP" text="Sistema nacional de pensiones"/></div>{form.pension==='AFP'&&<div className="mt-4"><Field label="AFP elegida"><Select value={form.afp} onChange={e=>set('afp',e.target.value)}><option>Integra</option><option>Prima</option><option>Profuturo</option><option>Habitat</option></Select></Field></div>}<div className="my-7 border-t border-slate-100"/><p className="mb-3 text-[11px] font-bold uppercase tracking-[.12em] text-slate-400">Salud</p><div className="grid gap-3 sm:grid-cols-2"><OptionCard active={form.health==='EsSalud'} onClick={()=>set('health','EsSalud')} icon={HeartPulse} title="EsSalud" text="Cobertura obligatoria de salud"/><OptionCard active={form.health==='EPS'} onClick={()=>set('health','EPS')} icon={BriefcaseBusiness} title="EPS" text="Cobertura complementaria privada"/></div>{form.health==='EPS'&&<div className="mt-4"><Field label="Entidad prestadora de salud"><input value={form.eps} onChange={e=>set('eps',e.target.value)} className={inputStyle} placeholder="Ej. Pacífico EPS"/></Field></div>}</> }

function ConfirmStep({ form }) { const name=`${form.firstName} ${form.lastName}`.trim()||'Colaborador pendiente'; return <><FormHeader icon={BadgeCheck} label="Paso 3 · Confirmación" title="Todo listo para guardar" text="Revisa el resumen. Podrás editar la ficha siempre que lo necesites."/><div className="divide-y divide-slate-100 overflow-hidden rounded-2xl border border-slate-200"><ReviewRow label="Persona" value={name} detail={`${form.documentType} ${form.document||'—'} · ${form.role||'Sin cargo'}`}/><ReviewRow label="Pensión" value={form.pension==='AFP'?`AFP ${form.afp}`:'ONP'} detail="Sistema previsional"/><ReviewRow label="Salud" value={form.health==='EPS'?`EPS ${form.eps||'por confirmar'}`:'EsSalud'} detail="Cobertura de salud"/><ReviewRow label="Ingreso" value={form.startDate||'Por definir'} detail="Fecha de inicio laboral"/></div><div className="mt-5 flex gap-3 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-900"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-emerald-600"/><p>La afiliación quedará registrada y disponible para completar con documentos o derechohabientes.</p></div></> }

function FormHeader({ icon, label, title, text }) { const HeaderIcon = icon; return <div className="mb-7"><div className="flex items-center gap-2 text-indigo-600"><HeaderIcon size={16}/><span className="text-[11px] font-bold uppercase tracking-[.12em]">{label}</span></div><h2 className="mt-3 text-xl font-semibold tracking-[-.02em] text-slate-950">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div> }
function OptionCard({ active, onClick, icon, title, text }) { const CardIcon = icon; return <button type="button" onClick={onClick} className={`rounded-2xl border p-4 text-left transition ${active?'border-indigo-500 bg-indigo-50':'border-slate-200 hover:border-slate-300 hover:bg-slate-50'}`}><div className="flex items-start justify-between"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${active?'bg-indigo-600 text-white':'bg-slate-100 text-slate-500'}`}><CardIcon size={18}/></span>{active&&<span className="flex h-5 w-5 items-center justify-center rounded-full bg-indigo-600 text-white"><Check size={12} strokeWidth={3}/></span>}</div><p className="mt-3 text-sm font-semibold text-slate-900">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></button> }
function ReviewRow({ label, value, detail }) { return <div className="flex items-center justify-between gap-5 p-4"><div><p className="text-[11px] font-bold uppercase tracking-[.1em] text-slate-400">{label}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div><p className="max-w-[55%] text-right text-sm font-semibold text-slate-900">{value}</p></div> }
function DraftCard({ form, step }) { const name=`${form.firstName} ${form.lastName}`.trim(); return <aside className="h-fit rounded-2xl bg-slate-950 p-5 text-white lg:sticky lg:top-7"><div className="flex items-center justify-between"><span className="text-[11px] font-bold uppercase tracking-[.12em] text-slate-400">Ficha en curso</span><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] font-bold text-slate-200">{step}/3</span></div><div className="mt-6 flex items-center gap-3"><Avatar size="lg" initials={name?name.split(' ').map(word=>word[0]).slice(0,2).join(''):'+'} color="bg-gradient-to-br from-indigo-400 to-violet-400 text-white"/><div><p className="text-sm font-semibold">{name||'Nueva persona'}</p><p className="mt-0.5 text-xs text-slate-400">{form.role||'Cargo por definir'}</p></div></div><div className="my-6 h-px bg-white/10"/><div className="space-y-4"><DraftRow label="Pensión" value={form.pension==='AFP'?`AFP ${form.afp}`:form.pension}/><DraftRow label="Salud" value={form.health==='EPS'?`EPS ${form.eps||'—'}`:form.health}/><DraftRow label="Ingreso" value={form.startDate||'Pendiente'}/></div><div className="mt-7 rounded-xl bg-white/7 p-3 text-xs leading-5 text-slate-300">Los documentos y derechohabientes se gestionan después de guardar esta ficha.</div></aside> }
function DraftRow({ label, value }) { return <div className="flex items-center justify-between gap-3"><span className="text-xs text-slate-400">{label}</span><span className="text-right text-xs font-semibold text-white">{value}</span></div> }
function RemoveDialog({ person, onCancel, onConfirm }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-5"><section role="alertdialog" aria-modal="true" aria-labelledby="remove-title" className="w-full max-w-sm rounded-2xl bg-white p-6 shadow-2xl"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-rose-50 text-rose-600"><Trash2 size={19}/></div><h2 id="remove-title" className="mt-4 text-lg font-semibold text-slate-950">¿Retirar esta ficha?</h2><p className="mt-2 text-sm leading-6 text-slate-500">{person.name} dejará de aparecer en el listado. Esta acción es solo de demostración.</p><div className="mt-6 flex justify-end gap-2"><button onClick={onCancel} className="rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50">Cancelar</button><button onClick={onConfirm} className="rounded-xl bg-rose-600 px-3 py-2.5 text-sm font-semibold text-white hover:bg-rose-700">Retirar ficha</button></div></section></div> }

createRoot(document.getElementById('root')).render(<App />)
